onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - sharp

overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  cookie@<0.7.0: '>=0.7.0'
  form-data@<2.5.4: '>=2.5.4'
  glob-parent: ^6.0.1
  happy-dom@<20.0.0: '>=20.0.0'
  postcss: ^8.2.10
  rollup: 4.52.4
  styled-components: ^6
  tough-cookie@<4.1.3: '>=4.1.3'

publicHoistPattern:
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'
