import type { RuleName } from '@betagouv/france-chaleur-urbaine-publicodes';

const labels: Partial<Record<RuleName, string>> = {
  'amortissement . taux actualisation': 'Taux actualisation',
  'augmenter la température de chauffe': 'augmenter la température de chauffe',
  'besoins chauffage par appartement': 'besoins chauffage par appartement',
  'besoins eau chaude sanitaire par appartement': 'besoins eau chaude sanitaire par appartement',
  'besoins en climatisation par appartement': 'besoins en climatisation par appartement',
  'chaudière à granulés . installation . puissance retenue': 'Gamme de puissance',
  'chaudière à granulés . ratios . conso auxiliaire': 'Consommation auxiliaire',
  'chaudière à granulés . ratios . conso combustible': 'Consommation combustible',
  'chaudière à granulés . ratios . durée de vie': 'Durée de vie',
  'chaudière à granulés . ratios . gros entretien P3': 'P3 Chaudière à granulés collectif',
  'chaudière à granulés . ratios . investissement équipement': 'Coût investissement',
  'chaudière à granulés . ratios . petit entretien P2': 'P2 Chaudière à granulés collectif',
  'chaudière à granulés . ratios . rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'combustibles . fioul . prix livraison incluse': 'Prix livraison incluse',
  'combustibles . fioul . TICPE': 'TICPE',
  'combustibles . fioul . TVA': 'TVA',
  'combustibles . gaz . abonnement part fixe collectif ou tertiaire': 'Abonnement Part Fixe collectif ou tertiaire',
  'combustibles . gaz . abonnement part fixe individuel': 'Abonnement Part Fixe individuel',
  'combustibles . gaz . abonnement part fixe individuel . coût distribution HT': 'Abonnement Coût distribution HT',
  'combustibles . gaz . abonnement part fixe individuel . coûts commerciaux hors CEE HT': 'Abonnement Coût commerciaux hors CEE HT',
  'combustibles . gaz . consommation part variable TTC': 'Consommation Part Variable TTC',
  'combustibles . gaz . coût de la molécule HT': 'Coût de la molécule HT',
  'combustibles . gaz . coût de transport HT': 'Coût de transport HT',
  'combustibles . gaz . coût des CEE HT': 'Coût des CEE HT',
  'combustibles . gaz . coût distribution HT': 'Coût distribution HT',
  'combustibles . gaz . puissance souscrite collectif ou tertiaire': 'Puissance souscrite pour calcul installation collective ou tertiaire',
  'combustibles . gaz . taxes . CTA': "Contribution tarifaire d'acheminement CTA",
  'combustibles . gaz . taxes . TICGN': 'Taxe intérieure de consommation sur le gaz naturel TICGN',
  'combustibles . gaz . taxes . TVA part fixe': 'TVA Part fixe',
  'combustibles . gaz . taxes . TVA part variable': 'TVA part variable',
  'combustibles . granulés . prix pour les granulés': 'Prix pour les granulés',
  'combustibles . granulés . TVA': 'TVA',
  'combustibles . granulés . type de conditionnement': 'Type de conditionnement',
  'combustibles . réseau de chaleur . abonnement': 'Tarification R2 (Part fixe)',
  'combustibles . réseau de chaleur . consommation': 'Tarification R1 (Part variable)',
  'combustibles . réseau de chaleur . coût': 'Coût',
  'combustibles . réseau de chaleur . part fixe': 'Part fixe',
  'combustibles . réseau de chaleur . part variable': 'Part variable',
  'combustibles . électricité . abonnement part fixe collectif': 'Abonnement Part Fixe coll',
  'combustibles . électricité . abonnement part fixe individuel': 'Abonnement Part Fixe indiv',
  'combustibles . électricité . option tarifaire': 'Option tarifaire',
  'combustibles . électricité . part variable heure creuse': 'Consommation Part variable en heure creuse',
  'combustibles . électricité . part variable heure pleine': 'Consommation Part variable en heure pleine',
  'combustibles . électricité . puissance souscrite collectif': 'Puissance souscrite coll',
  'combustibles . électricité . puissance souscrite individuel': 'Puissance souscrite indiv',
  'combustibles . électricité . tarifs . option heures creuses . part de la consommation en HC': 'Part de la consommation en HC',
  'combustibles . électricité . tarifs . option heures creuses . part de la consommation en HP': 'Part de la consommation en HP',
  'combustibles . électricité . taxes . Part Fixe x TVA': 'TVA Part Fixe',
  "combustibles . électricité . taxes . Part Variable x Accise sur l'électricité ex TIPCSE CSPE": "Accise sur l'électricité ex TIPCSE CSPE",
  'combustibles . électricité . taxes . Part Variable x TVA': 'TVA Part Variable',
  'consommation spécifique chauffage': 'consommation spécifique chauffage',
  'consommation spécifique climatisation': 'consommation spécifique climatisation par habitant',
  'consommation spécifique ECS': 'consommation spécifique ECS',
  DPE: 'DPE',
  'degré jours unifié spécifique chaud': 'degré jours unifié spécifique chaud',
  'degré jours unifié spécifique froid': 'degré jours unifié spécifique froid',
  'ecs additionnelle . capacité du ballon électrique': 'Capacité chauffe eau électrique à accumulation',
  'ecs additionnelle . coût des panneaux solaires': 'Chauffe-eau solaire prix panneaux',
  'ecs additionnelle . coût du chauffe-eau solaire': 'Chauffe-eau x solaire',
  'ecs additionnelle . coût du chauffe-eau électrique': 'Chauffe-eau électrique à accumulation',
  'ecs additionnelle . durée de vie chauffe-eau solaire': 'Durée de vie',
  'ecs additionnelle . durée de vie chauffe-eau électrique': 'Durée de vie',
  'ecs additionnelle . gros entretien P3 chauffe-eau solaire': 'P3 Chauffe-eau solaire',
  'ecs additionnelle . gros entretien P3 chauffe-eau électrique': 'P3 Chauffe-eau électrique à accumulation',
  'ecs additionnelle . part du solaire dans la production': "Part du solaire dans la production d'ECS",
  'ecs additionnelle . petit entretien P2 chauffe-eau solaire': 'P2 Chauffe-eau solaire',
  'ecs additionnelle . petit entretien P2 chauffe-eau électrique': 'P2 Chauffe-eau électrique à accumulation',
  'ecs additionnelle . rendement stockage ballon solaire': 'Rendement stockage ballon',
  'ecs additionnelle . rendement stockage ballon électrique': 'Rendement stockage ballon',
  'ecs additionnelle . surface de panneaux': 'Surface de panneau nécessaire',
  'fioul coll . installation . puissance retenue': 'Gamme de puissance',
  'fioul coll . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'fioul coll . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'fioul coll . ratios . conso combustible': 'Consommation combustible',
  'fioul coll . ratios . durée de vie': 'Durée de vie',
  'fioul coll . ratios . gros entretien P3': 'P3 Fioul collectif',
  'fioul coll . ratios . investissement équipement': 'Coût investissement',
  'fioul coll . ratios . petit entretien P2': 'P2 Fioul collectif',
  'fioul coll . ratios . rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'fioul coll . ratios . rendement chaudière ECS': 'Rendement chaudière ECS',
  'fioul indiv . installation . puissance retenue': 'Gamme de puissance',
  'fioul indiv . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'fioul indiv . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'fioul indiv . ratios . conso combustible': 'Consommation combustible',
  'fioul indiv . ratios . durée de vie': 'Durée de vie',
  'fioul indiv . ratios . gros entretien P3': 'P3 Fioul individuel',
  'fioul indiv . ratios . investissement équipement': 'Coût investissement',
  'fioul indiv . ratios . petit entretien P2': 'P2 Fioul individuel',
  'fioul indiv . ratios . rendement chaudière': 'Rendement chaudière',
  'gaz coll avec cond . installation . puissance retenue': 'Gamme de puissance',
  'gaz coll avec cond . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'gaz coll avec cond . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'gaz coll avec cond . ratios . conso combustible': 'Consommation combustible',
  'gaz coll avec cond . ratios . durée de vie': 'Durée de vie',
  'gaz coll avec cond . ratios . gros entretien P3': 'P3 Gaz collectif avec condensation',
  'gaz coll avec cond . ratios . investissement équipement': 'Coût investissement',
  'gaz coll avec cond . ratios . petit entretien P2': 'P2 Gaz collectif avec condensation',
  'gaz coll avec cond . ratios . rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'gaz coll avec cond . ratios . rendement chaudière ECS': 'Rendement chaudière ECS',
  'gaz coll sans cond . installation . puissance retenue': 'Gamme de puissance',
  'gaz coll sans cond . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'gaz coll sans cond . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'gaz coll sans cond . ratios . conso combustible': 'Consommation combustible',
  'gaz coll sans cond . ratios . durée de vie': 'Durée de vie',
  'gaz coll sans cond . ratios . gros entretien P3': 'P3 Gaz collectif sans condensation',
  'gaz coll sans cond . ratios . investissement équipement': 'Coût investissement',
  'gaz coll sans cond . ratios . petit entretien P2': 'P2 Gaz collectif sans condensation',
  'gaz coll sans cond . ratios . rendement chaudière': 'Rendement chaudière',
  'gaz indiv avec cond . installation . puissance retenue': 'Gamme de puissance',
  'gaz indiv avec cond . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'gaz indiv avec cond . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'gaz indiv avec cond . ratios . conso combustible': 'Consommation combustible',
  'gaz indiv avec cond . ratios . durée de vie': 'Durée de vie',
  'gaz indiv avec cond . ratios . gros entretien P3': 'P3 Gaz individuel avec condensation',
  'gaz indiv avec cond . ratios . investissement équipement': 'Coût investissement',
  'gaz indiv avec cond . ratios . petit entretien P2': 'P2 Gaz individuel avec condensation',
  'gaz indiv avec cond . ratios . rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'gaz indiv avec cond . ratios . rendement chaudière ECS': 'Rendement chaudière ECS',
  'gaz indiv sans cond . installation . puissance retenue': 'Gamme de puissance',
  'gaz indiv sans cond . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'gaz indiv sans cond . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'gaz indiv sans cond . ratios . conso combustible': 'Consommation combustible',
  'gaz indiv sans cond . ratios . durée de vie': 'Durée de vie',
  'gaz indiv sans cond . ratios . gros entretien P3': 'P3 Gaz individuel sans condensation',
  'gaz indiv sans cond . ratios . investissement équipement': 'Coût investissement',
  'gaz indiv sans cond . ratios . petit entretien P2': 'P2 Gaz individuel sans condensation',
  'gaz indiv sans cond . ratios . rendement chaudière': 'Rendement chaudière',
  'investissement . pose et mise en place': "Pose et mise en place de l'installation",
  'investissement . TVA': 'TVA',
  'méthode résidentiel': 'Méthode de calcul pour les besoins en chauffage et refroidissement',
  'méthode tertiaire': 'Méthode de calcul pour les besoins en chauffage et refroidissement',
  "Nombre d'habitants moyen par appartement": "Nombre d'habitants moyen par appartement",
  "nombre de logements dans l'immeuble concerné": "Nombre de logements dans l'immeuble concerné",
  'normes thermiques et âge du bâtiment': 'Normes thermiques et âge du bâtiment',
  'normes thermiques tertiaire': 'Normes thermiques tertiaire',
  'PAC air-air coll . installation . puissance retenue': 'Gamme de puissance',
  'PAC air-air coll . ratios . durée de vie': 'Durée de vie',
  'PAC air-air coll . ratios . investissement équipement': 'Coût investissement',
  'PAC air-air coll . ratios . SCOP': 'SCOP',
  'PAC air-air coll . ratios . SEER': 'SEER',
  'PAC air-air indiv . installation . puissance retenue': 'Gamme de puissance',
  'PAC air-air indiv . ratios . durée de vie': 'Durée de vie',
  'PAC air-air indiv . ratios . investissement équipement': 'Coût investissement',
  'PAC air-air indiv . ratios . SCOP': 'SCOP',
  'PAC air-air indiv . ratios . SEER': 'SEER',
  'PAC air-eau coll . installation . puissance retenue': 'Gamme de puissance',
  'PAC air-eau coll . ratios . durée de vie': 'Durée de vie',
  'PAC air-eau coll . ratios . investissement équipement': 'Coût investissement',
  'PAC air-eau coll . ratios . SCOP': 'SCOP',
  'PAC air-eau coll . ratios . SEER': 'SEER',
  'PAC air-eau indiv . installation . puissance retenue': 'Gamme de puissance',
  'PAC air-eau indiv . ratios . durée de vie': 'Durée de vie',
  'PAC air-eau indiv . ratios . investissement équipement': 'Coût investissement',
  'PAC air-eau indiv . ratios . SCOP': 'SCOP',
  'PAC air-eau indiv . ratios . SEER': 'SEER',
  'PAC eau-eau coll . installation . puissance retenue': 'Gamme de puissance',
  'PAC eau-eau coll . ratios . investissement captage champ de sondes': 'Coûts captage sous-sol champs sur sonde',
  'PAC eau-eau coll . ratios . investissement hors captage': 'Coûts hors captage sous-sol',
  'PAC eau-eau coll . ratios . investissement équipement': 'Coût investissement',
  'PAC eau-eau coll . ratios . SCOP champ de sondes': 'SCOP',
  'PAC eau-eau indiv . installation . puissance retenue': 'Gamme de puissance',
  'PAC eau-eau indiv . ratios . durée de vie': 'Durée de vie',
  'PAC eau-eau indiv . ratios . investissement équipement': 'Coût investissement',
  'PAC eau-eau indiv . ratios . SCOP capteurs horizontaux': 'SCOP',
  'Paramètres économiques . Aides . Aides x Éligible CEE': 'Éligible CEE',
  'Paramètres économiques . Aides . Aides x Éligible Coup de pouce chauffage': 'Éligible Coup de pouce chauffage',
  "Paramètres économiques . Aides . Aides x Éligible Ma prime renov'": "Éligible Ma prime renov'",
  'Paramètres économiques . Aides . Valeur CEE': 'Valeur CEE',
  "Paramètres économiques . Aides . Éligibilité x Je dispose actuellement d'une chaudière gaz ou fioul":
    "Je dispose actuellement d'une chaudière gaz ou fioul",
  'Paramètres économiques . Aides . Éligibilité x Je suis un particulier': 'Je suis un particulier',
  'Paramètres économiques . Aides . Éligibilité x Prise en compte des aides': 'Prise en compte des aides',
  'Paramètres économiques . Aides . Éligibilité x Ressources du ménage': 'Ressources du ménage',
  'Paramètres économiques . Gros entretien P3 . TVA': 'P3 TVA',
  'Paramètres économiques . Petit entretien P2 . TVA': 'P2 TVA',
  'Part de la surface à climatiser': 'Part de la surface à climatiser',
  'Production eau chaude sanitaire': "Inclure la production d'eau chaude sanitaire",
  'poêle à granulés . installation . puissance retenue': 'Gamme de puissance',
  'poêle à granulés . ratios . conso combustible': 'Consommation combustible',
  'poêle à granulés . ratios . durée de vie': 'Durée de vie',
  'poêle à granulés . ratios . gros entretien P3': 'P3 Poêle à granulés individuel',
  'poêle à granulés . ratios . investissement équipement': 'Coût investissement',
  'poêle à granulés . ratios . petit entretien P2': 'P2 Poêle à granulés individuel',
  'poêle à granulés . ratios . rendement poêle chauffage': 'Rendement poêle chauffage',
  'radiateur électrique . installation . puissance retenue': 'Gamme de puissance',
  'radiateur électrique . ratios . conso combustible': 'Consommation combustible',
  'radiateur électrique . ratios . durée de vie': 'Durée de vie',
  'radiateur électrique . ratios . gros entretien P3': 'P3 Radiateur électrique',
  'radiateur électrique . ratios . investissement équipement': 'Coût investissement',
  'radiateur électrique . ratios . petit entretien P2': 'P2 Radiateur électrique',
  'radiateur électrique . ratios . rendement': 'Rendement',
  'ratios . PUIS Coefficient de foisonnement chauffage collectif': 'Coefficient de foisonnement chauffage collectif',
  'ratios . PUIS Coefficient de foisonnement ECS': 'Coefficient de foisonnement ECS',
  'ratios . PUIS Facteur de surpuissance': 'Facteur de surpuissance',
  'ratios . PUIS Nombre heure de fonctionnement non climatique ECS': 'Nombre heure de fonctionnement non climatique ECS',
  'ratios . PUIS Température de non chauffage': 'Température de non chauffage',
  'réseau de chaleur . installation . puissance retenue': 'Gamme de puissance',
  'réseau de chaleur . ratios . conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'réseau de chaleur . ratios . conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'réseau de chaleur . ratios . durée avant renouvellement': 'Durée avant renouvellement',
  'réseau de chaleur . ratios . frais de raccordement': 'Coût investissement raccordement au réseau',
  'réseau de chaleur . ratios . gros entretien P3': 'P3 RCU',
  'réseau de chaleur . ratios . petit entretien P2': 'P2 RCU',
  'réseau de chaleur . ratios . rendement sous station chauffage': 'Rendement sous-station chauffage',
  'réseau de chaleur . ratios . rendement sous station ECS': 'Rendement sous station ECS',
  'réseau de froid . installation . puissance retenue': 'Gamme de puissance',
  'réseau de froid . ratios . conso auxiliaire': 'Consommation auxiliaire',
  'réseau de froid . ratios . durée de vie': 'Durée de vie',
  'réseau de froid . ratios . gros entretien P3': 'P3 RFU',
  'réseau de froid . ratios . petit entretien P2': 'P2 RFU',
  'réseau de froid . ratios . rendement sous station': 'Rendement sous station',
  'sous zone climatique': 'Sous-zone climatique',
  'surface logement type tertiaire': 'Surface',
  'Température émetteurs': 'Température émetteurs',
  'température de référence chaud': 'température de référence chaud',
  'type de bâtiment': 'Type de bâtiment',
  'type de production de froid': 'Inclure la climatisation',
  'type de production ECS': "Inclure la production d'eau chaude sanitaire",
  'zone climatique': 'Zone climatique',
};

/**
 * Libellé d'affichage d'une règle, ou undefined si elle n'en a pas.
 * Point d'entrée pour les clés issues d'une situation runtime, non typées.
 */
export const getRuleLabel = (ruleName: string) => labels[ruleName as RuleName];

export default labels;
