const labels: { [key: string]: string } = {
  'Abonnement x Part Fixe TTC collectif ou tertiaire': 'Abonnement Part fixe',
  'augmenter la température de chauffe': 'augmenter la température de chauffe',
  'besoins chauffage par appartement': 'besoins chauffage par appartement',
  'besoins eau chaude sanitaire par appartement': 'besoins eau chaude sanitaire par appartement',
  'besoins en climatisation par appartement': 'besoins en climatisation par appartement',
  "Calcul Eco . Coût d'achat du combustible . Chaleur RCU x Part abonnement": 'Tarification R2 (Part fixe)',
  "Calcul Eco . Coût d'achat du combustible . Chaleur RCU x Part consommation": 'Tarification R1 (Part variable)',
  'Coût investissement x Chaudière à granulés coll': 'Coût investissement',
  'Coût investissement x frais de raccordement au réseaux x RCU': 'Frais de raccordement au réseaux',
  'Coût investissement x Groupe eau glacée x tertiaire': 'Coût investissement',
  'Coût investissement x Groupe froid x résidentiel': 'Coût investissement',
  'Coût investissement x Poêle à granulés indiv': 'Coût investissement',
  'consommation spécifique chauffage': 'consommation spécifique chauffage',
  'consommation spécifique climatisation': 'consommation spécifique climatisation par habitant',
  'consommation spécifique ECS': 'consommation spécifique ECS',
  DPE: 'DPE',
  'degré jours unifié spécifique chaud': 'degré jours unifié spécifique chaud',
  'degré jours unifié spécifique froid': 'degré jours unifié spécifique froid',
  'Installation x Chaudière à granulés coll x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Fioul coll x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Fioul indiv x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Gaz coll avec cond x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Gaz coll sans cond x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Gaz indiv avec cond x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Gaz indiv sans cond x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC air-air x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC air-air x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC air-eau x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC air-eau x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC eau-eau x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x PAC eau-eau x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Poêle à granulés indiv x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Radiateur électrique x Individuel . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Réseaux de chaleur x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Installation x Réseaux de froid x Collectif . gamme de puissance existante': 'Gamme de puissance',
  'Investissement x Chaudière à granulés coll': 'Coût investissement',
  'Investissement x frais de raccordement au réseaux x RCU': 'Coût investissement raccordement au réseau',
  'Investissement x Poêle à granulés indiv': 'Coût investissement',
  'méthode résidentiel': 'Méthode de calcul pour les besoins en chauffage et refroidissement',
  'méthode tertiaire': 'Méthode de calcul pour les besoins en chauffage et refroidissement',
  "Nombre d'habitants moyen par appartement": "Nombre d'habitants moyen par appartement",
  "nombre de logements dans l'immeuble concerné": "Nombre de logements dans l'immeuble concerné",
  'normes thermiques et âge du bâtiment': 'Normes thermiques et âge du bâtiment',
  'normes thermiques tertiaire': 'Normes thermiques tertiaire',
  'Paramètres économiques . Aides . Aides x Éligible CEE': 'Éligible CEE',
  'Paramètres économiques . Aides . Aides x Éligible Coup de pouce chauffage': 'Éligible Coup de pouce chauffage',
  "Paramètres économiques . Aides . Aides x Éligible Ma prime renov'": "Éligible Ma prime renov'",
  'Paramètres économiques . Aides . Valeur CEE': 'Valeur CEE',
  "Paramètres économiques . Aides . Éligibilité x Je dispose actuellement d'une chaudière gaz ou fioul":
    "Je dispose actuellement d'une chaudière gaz ou fioul",
  'Paramètres économiques . Aides . Éligibilité x Je suis un particulier': 'Je suis un particulier',
  'Paramètres économiques . Aides . Éligibilité x Prise en compte des aides': 'Prise en compte des aides',
  'Paramètres économiques . Aides . Éligibilité x Ressources du ménage': 'Ressources du ménage',
  'Paramètres économiques . Electricité x Abonnement Part Fixe coll': 'Abonnement Part Fixe coll',
  'Paramètres économiques . Electricité x Abonnement Part Fixe indiv': 'Abonnement Part Fixe indiv',
  'Paramètres économiques . Electricité x Consommation Part variable en heure creuse': 'Consommation Part variable en heure creuse',
  'Paramètres économiques . Electricité x Consommation Part variable en heure pleine': 'Consommation Part variable en heure pleine',
  'Paramètres économiques . Electricité x Option tarifaire': 'Option tarifaire',
  'Paramètres économiques . Electricité x Puissance souscrite coll': 'Puissance souscrite coll',
  'Paramètres économiques . Electricité x Puissance souscrite indiv': 'Puissance souscrite indiv',
  'Paramètres économiques . Electricité x Taxe . Part Fixe x TVA': 'TVA Part Fixe',
  "Paramètres économiques . Electricité x Taxe . Part Variable x Accise sur l'électricité ex TIPCSE CSPE":
    "Accise sur l'électricité ex TIPCSE CSPE",
  'Paramètres économiques . Electricité x Taxe . Part Variable x TVA': 'TVA Part Variable',
  'Paramètres économiques . Fioul . Prix livraison incluse': 'Prix livraison incluse',
  'Paramètres économiques . Fioul . TICPE': 'TICPE',
  'Paramètres économiques . Fioul . TVA': 'TVA',
  'Paramètres économiques . Gaz x Abonnement x Part Fixe TTC collectif ou tertiaire': 'Abonnement Part Fixe collectif ou tertiaire',
  'Paramètres économiques . Gaz x Abonnement x Part Fixe TTC individuel': 'Abonnement Part Fixe individuel',
  'Paramètres économiques . Gaz x Abonnement x Part Fixe TTC individuel x Coût commerciaux hors CEE HT':
    'Abonnement Coût commerciaux hors CEE HT',
  'Paramètres économiques . Gaz x Abonnement x Part Fixe TTC individuel x Coût distribution HT': 'Abonnement Coût distribution HT',
  'Paramètres économiques . Gaz x Consommation x Part Variable TTC': 'Consommation Part Variable TTC',
  'Paramètres économiques . Gaz x Coût de la molécule HT': 'Coût de la molécule HT',
  'Paramètres économiques . Gaz x Coût de transport HT': 'Coût de transport HT',
  'Paramètres économiques . Gaz x Coût des CEE HT': 'Coût des CEE HT',
  'Paramètres économiques . Gaz x Coût distribution HT': 'Coût distribution HT',
  'Paramètres économiques . Gaz x Puissance souscrite pour calcul installation collective ou tertiaire':
    'Puissance souscrite pour calcul installation collective ou tertiaire',
  "Paramètres économiques . Gaz x Taxe x Part fixe x Contribution tarifaire d'acheminement CTA":
    "Contribution tarifaire d'acheminement CTA",
  'Paramètres économiques . Gaz x Taxe x Part fixe x TVA': 'TVA Part fixe',
  'Paramètres économiques . Gaz x Taxe x Part variable x Taxe intérieure de consommation sur le gaz naturel TICGN':
    'Taxe intérieure de consommation sur le gaz naturel TICGN',
  'Paramètres économiques . Gaz x Taxe x Part variable x TVA': 'TVA part variable',
  'Paramètres économiques . Granulés . Prix pour les granulés': 'Prix pour les granulés',
  'Paramètres économiques . Granulés . TVA': 'TVA',
  'Paramètres économiques . Granulés . Type de conditionnement': 'Type de conditionnement',
  'Paramètres économiques . Gros entretien P3 . Chaudière à granulés coll': 'P3 Chaudière à granulés collectif',
  'Paramètres économiques . Gros entretien P3 . Chauffe-eau solaire': 'P3 Chauffe-eau solaire',
  'Paramètres économiques . Gros entretien P3 . Chauffe-eau électrique à accumulation': 'P3 Chauffe-eau électrique à accumulation',
  'Paramètres économiques . Gros entretien P3 . Fioul coll': 'P3 Fioul collectif',
  'Paramètres économiques . Gros entretien P3 . Fioul indiv': 'P3 Fioul individuel',
  'Paramètres économiques . Gros entretien P3 . Gaz coll avec cond': 'P3 Gaz collectif avec condensation',
  'Paramètres économiques . Gros entretien P3 . Gaz coll sans cond': 'P3 Gaz collectif sans condensation',
  'Paramètres économiques . Gros entretien P3 . Gaz indiv avec cond': 'P3 Gaz individuel avec condensation',
  'Paramètres économiques . Gros entretien P3 . Gaz indiv sans cond': 'P3 Gaz individuel sans condensation',
  'Paramètres économiques . Gros entretien P3 . PAC air-air': 'P3 PAC air-air',
  'Paramètres économiques . Gros entretien P3 . PAC air-eau': 'P3 PAC air-eau',
  'Paramètres économiques . Gros entretien P3 . PAC eau-eau': 'P3 PAC eau-eau',
  'Paramètres économiques . Gros entretien P3 . Poêle à granulés indiv': 'P3 Poêle à granulés individuel',
  'Paramètres économiques . Gros entretien P3 . Radiateur électrique': 'P3 Radiateur électrique',
  'Paramètres économiques . Gros entretien P3 . RCU': 'P3 RCU',
  'Paramètres économiques . Gros entretien P3 . RFU': 'P3 RFU',
  'Paramètres économiques . Gros entretien P3 . TVA': 'P3 TVA',
  'Paramètres économiques . Petit entretien P2 . Chaudière à granulés coll': 'P2 Chaudière à granulés collectif',
  'Paramètres économiques . Petit entretien P2 . Chauffe-eau solaire': 'P2 Chauffe-eau solaire',
  'Paramètres économiques . Petit entretien P2 . Chauffe-eau électrique à accumulation': 'P2 Chauffe-eau électrique à accumulation',
  'Paramètres économiques . Petit entretien P2 . Fioul coll': 'P2 Fioul collectif',
  'Paramètres économiques . Petit entretien P2 . Fioul indiv': 'P2 Fioul individuel',
  'Paramètres économiques . Petit entretien P2 . Gaz coll avec cond': 'P2 Gaz collectif avec condensation',
  'Paramètres économiques . Petit entretien P2 . Gaz coll sans cond': 'P2 Gaz collectif sans condensation',
  'Paramètres économiques . Petit entretien P2 . Gaz indiv avec cond': 'P2 Gaz individuel avec condensation',
  'Paramètres économiques . Petit entretien P2 . Gaz indiv sans cond': 'P2 Gaz individuel sans condensation',
  'Paramètres économiques . Petit entretien P2 . PAC air-air': 'P2 PAC air-air',
  'Paramètres économiques . Petit entretien P2 . PAC air-eau': 'P2 PAC air-eau',
  'Paramètres économiques . Petit entretien P2 . PAC eau-eau': 'P2 PAC eau-eau',
  'Paramètres économiques . Petit entretien P2 . Poêle à granulés indiv': 'P2 Poêle à granulés individuel',
  'Paramètres économiques . Petit entretien P2 . Radiateur électrique': 'P2 Radiateur électrique',
  'Paramètres économiques . Petit entretien P2 . RCU': 'P2 RCU',
  'Paramètres économiques . Petit entretien P2 . RFU': 'P2 RFU',
  'Paramètres économiques . Petit entretien P2 . TVA': 'P2 TVA',
  'Paramètres économiques . Réseaux chaleur . Coût': 'Coût',
  'Paramètres économiques . Réseaux chaleur . Part fixe': 'Part fixe',
  'Paramètres économiques . Réseaux chaleur . Part variable': 'Part variable',
  'Part de la surface à climatiser': 'Part de la surface à climatiser',
  'Production eau chaude sanitaire': "Inclure la production d'eau chaude sanitaire",
  'Puissance installation x Capacité chauffe eau solaire': 'Capacité chauffe eau solaire',
  'Puissance installation x Capacité chauffe eau électrique à accumulation': 'Capacité chauffe eau électrique à accumulation',
  'ratios . CHAUF EAU ELEC Durée de vie': 'Durée de vie',
  'ratios . CHAUF EAU ELEC Rendement stockage ballon': 'Rendement stockage ballon',
  'ratios . CHAUF EAU SOLAIRE Durée de vie': 'Durée de vie',
  "ratios . CHAUF EAU SOLAIRE Part du solaire dans la production d'ECS": "Part du solaire dans la production d'ECS",
  'ratios . CHAUF EAU SOLAIRE Rendement stockage ballon': 'Rendement stockage ballon',
  'ratios . FIOUL COLL Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . FIOUL COLL Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . FIOUL COLL Conso combustible': 'Consommation combustible',
  'ratios . FIOUL COLL Durée de vie': 'Durée de vie',
  'ratios . FIOUL COLL Rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'ratios . FIOUL COLL Rendement chaudière ECS': 'Rendement chaudière ECS',
  'ratios . FIOUL IND Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . FIOUL IND Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . FIOUL IND Conso combustible': 'Consommation combustible',
  'ratios . FIOUL IND Durée de vie': 'Durée de vie',
  'ratios . FIOUL IND Rendement chaudière': 'Rendement chaudière',
  'ratios . GAZ COLL COND Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . GAZ COLL COND Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . GAZ COLL COND Conso combustible': 'Consommation combustible',
  'ratios . GAZ COLL COND Durée de vie': 'Durée de vie',
  'ratios . GAZ COLL COND Rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'ratios . GAZ COLL COND Rendement chaudière ECS': 'Rendement chaudière ECS',
  'ratios . GAZ COLL SCOND Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . GAZ COLL SCOND Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . GAZ COLL SCOND Conso combustible': 'Consommation combustible',
  'ratios . GAZ COLL SCOND Durée de vie': 'Durée de vie',
  'ratios . GAZ COLL SCOND Rendement chaudière': 'Rendement chaudière',
  'ratios . GAZ IND COND Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . GAZ IND COND Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . GAZ IND COND Conso combustible': 'Consommation combustible',
  'ratios . GAZ IND COND Durée de vie': 'Durée de vie',
  'ratios . GAZ IND COND Rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'ratios . GAZ IND COND Rendement chaudière ECS': 'Rendement chaudière ECS',
  'ratios . GAZ IND SCOND Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . GAZ IND SCOND Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . GAZ IND SCOND Conso combustible': 'Consommation combustible',
  'ratios . GAZ IND SCOND Durée de vie': 'Durée de vie',
  'ratios . GAZ IND SCOND Rendement chaudière': 'Rendement chaudière',
  'ratios . GRA CHAUD Conso auxiliaire': 'Consommation auxiliaire',
  'ratios . GRA CHAUD Conso combustible': 'Consommation combustible',
  'ratios . GRA CHAUD Durée de vie': 'Durée de vie',
  'ratios . GRA CHAUD Rendement chaudière chauffage': 'Rendement chaudière chauffage',
  'ratios . GRA CHAUD Rendement chaudière ECS': 'Rendement chaudière ECS',
  'ratios . GRA POELE Conso combustible': 'Consommation combustible',
  'ratios . GRA POELE Durée de vie': 'Durée de vie',
  'ratios . GRA POELE Rendement poêle chauffage': 'Rendement poêle chauffage',
  'ratios . PAC AIR AIR Durée de vie coll': 'Durée de vie',
  'ratios . PAC AIR AIR Durée de vie indiv': 'Durée de vie',
  'ratios . PAC AIR AIR SCOP coll': 'SCOP',
  'ratios . PAC AIR AIR SCOP indiv': 'SCOP',
  'ratios . PAC AIR AIR SEER coll': 'SEER',
  'ratios . PAC AIR AIR SEER indiv': 'SEER',
  'ratios . PAC AIR EAU Durée de vie coll': 'Durée de vie',
  'ratios . PAC AIR EAU Durée de vie indiv': 'Durée de vie',
  'ratios . PAC AIR EAU SCOP coll': 'SCOP',
  'ratios . PAC AIR EAU SCOP indiv': 'SCOP',
  'ratios . PAC AIR EAU SEER coll': 'SEER',
  'ratios . PAC AIR EAU SEER indiv': 'SEER',
  'ratios . PAC EAU EAU Durée de vie': 'Durée de vie',
  'ratios . PAC EAU EAU SCOP coll champ de sondes': 'SCOP',
  'ratios . PAC EAU EAU SCOP indiv capteurs horizontaux': 'SCOP',
  'ratios . PUIS Coefficient de foisonnement chauffage collectif': 'Coefficient de foisonnement chauffage collectif',
  'ratios . PUIS Coefficient de foisonnement ECS': 'Coefficient de foisonnement ECS',
  'ratios . PUIS Facteur de surpuissance': 'Facteur de surpuissance',
  'ratios . PUIS Nombre heure de fonctionnement non climatique ECS': 'Nombre heure de fonctionnement non climatique ECS',
  'ratios . PUIS Température de non chauffage': 'Température de non chauffage',
  'ratios . RAD ELEC INDIV Conso combustible': 'Consommation combustible',
  'ratios . RAD ELEC INDIV Durée de vie': 'Durée de vie',
  'ratios . RAD ELEC INDIV Rendement': 'Rendement',
  'ratios . RCU Conso auxiliaire chauffage': 'Consommation auxiliaire chauffage',
  'ratios . RCU Conso auxiliaire ECS': 'Consommation auxiliaire ECS',
  'ratios . RCU Durée avant renouvellement': 'Durée avant renouvellement',
  'ratios . RCU Rendement sous station chauffage': 'Rendement sous-station chauffage',
  'ratios . RCU Rendement sous station ECS': 'Rendement sous station ECS',
  'ratios . RFU Conso auxiliaire': 'Consommation auxiliaire',
  'ratios . RFU Durée de vie': 'Durée de vie',
  'ratios . RFU Rendement sous station': 'Rendement sous station',
  'ratios économiques . Amortissement x Taux actualisation': 'Taux actualisation',
  'ratios économiques . Chauffe-eau x panneaux solaire thermique x coût investissement': 'Chauffe-eau solaire prix panneaux',
  'ratios économiques . Chauffe-eau x solaire x coût investissement': 'Chauffe-eau x solaire',
  'ratios économiques . Chauffe-eau x électrique à accumulation x coût investissement': 'Chauffe-eau électrique à accumulation',
  'ratios économiques . Coût des combustibles x Electricité . Heure pleine x Heure creuse . Part de la consommation en HC':
    'Part de la consommation en HC',
  'ratios économiques . Coût des combustibles x Electricité . Heure pleine x Heure creuse . Part de la consommation en HP':
    'Part de la consommation en HP',
  'ratios économiques . Fioul x collectif': 'Coût investissement',
  'ratios économiques . Fioul x indiv': 'Coût investissement',
  'ratios économiques . Gaz x coll avec cond': 'Coût investissement',
  'ratios économiques . Gaz x coll sans cond': 'Coût investissement',
  'ratios économiques . Gaz x indiv avec cond': 'Coût investissement',
  'ratios économiques . Gaz x indiv sans cond': 'Coût investissement',
  "ratios économiques . Investissement x Pose et mise en place de l'installation": "Pose et mise en place de l'installation",
  'ratios économiques . Investissement x TVA': 'TVA',
  'ratios économiques . PAC x air-air réversible x Collectif': 'Coût investissement',
  'ratios économiques . PAC x air-air réversible x Individuel': 'Coût investissement',
  'ratios économiques . PAC x air-eau réversible x Collectif': 'Coût investissement',
  'ratios économiques . PAC x air-eau réversible x Individuel': 'Coût investissement',
  'ratios économiques . PAC x eau-eau non réversible . Coûts captage sous-sol champs sur sonde': 'Coûts captage sous-sol champs sur sonde',
  'ratios économiques . PAC x eau-eau non réversible . Coûts hors captage sous-sol': 'Coûts hors captage sous-sol',
  'ratios économiques . PAC x eau-eau non réversible x Collectif': 'Coût investissement',
  'ratios économiques . PAC x eau-eau non réversible x Individuel': 'Coût investissement',
  'ratios économiques . Radiateur électrique x Individuel x investissement total': 'Coût investissement',
  'sous zone climatique': 'Sous-zone climatique',
  'surface de panneau nécessaire': 'Surface de panneau nécessaire',
  'surface logement type tertiaire': 'Surface',
  'Température émetteurs': 'Température émetteurs',
  'température de référence chaud': 'température de référence chaud',
  'type de bâtiment': 'Type de bâtiment',
  'type de production de froid': 'Inclure la climatisation',
  'type de production ECS': "Inclure la production d'eau chaude sanitaire",
  'zone climatique': 'Zone climatique',
};

export default labels;
