export type BatEnrBatiment = {
  ac1: boolean | null;
  ac2: boolean | null;
  ac3: boolean | null;
  ac4: boolean | null;
  ac4bis: boolean | null;
  adresse: string | null;
  batiment_construction_id: string | null;
  batiment_groupe_id: string | null;
  categorie_majoritaire: string | null;
  classe_bilan_dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
  couv_sondes_200_2025: number | null;
  couv_st_ecs_2025: number | null;
  dpe_representatif_logement_surface_habitable_immeuble: number | null;
  etat_ppa: string | null;
  ffo_bat_nb_log: number | null;
  geometry: GeoJSON.Geometry | null;
  gis_geo_profonde: boolean | null;
  gmi_nappe_200: number | null;
  gmi_sonde_200: number | null;
  place_nappe: boolean | null;
  pot_nappe: number | null;
  prod_st_mwh_an: number | null;
  propri_uni: string | null;
  type_energie_chauffage: string | null;
  type_energie_ecs: string | null;
  type_installation_chauffage: string | null;
  type_installation_ecs: string | null;
};
