import { useQueryState } from 'nuqs';
import { useMemo } from 'react';

import Link from '@/components/ui/Link';

import { searchDocs } from './search';

/**
 * Full-text search over the documentation pages (index generated by the CLI
 * command `pnpm doc:build-search-index`). Renders the search field and, when a query
 * is entered, the ranked results in place of the table of contents.
 */
export function DocSearch() {
  const [query, setQuery] = useQueryState('q', { defaultValue: '' });
  const trimmed = query.trim();
  const isSearching = trimmed.length >= 2;
  const results = useMemo(() => (isSearching ? searchDocs(trimmed) : []), [isSearching, trimmed]);
  const terms = useMemo(() => trimmed.split(/\s+/).filter((term) => term.length >= 2), [trimmed]);

  return (
    <div className="mb-6">
      <input
        type="search"
        className="fr-input max-w-xl"
        placeholder="Rechercher dans la documentation…"
        aria-label="Rechercher dans la documentation"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
      />
      {isSearching && (
        <div className="mt-4">
          {results.length === 0 ? (
            <p className="text-faded">Aucun résultat pour « {trimmed} ».</p>
          ) : (
            <ul className="flex flex-col gap-4 list-none p-0 m-0">
              {results.map((result) => (
                <li key={result.slug}>
                  <Link href={`/admin/doc/${result.slug}`} className="text-base font-medium">
                    {result.title}
                  </Link>
                  <p className="text-sm text-faded mt-1 mb-0">
                    <Highlight text={result.snippet} terms={terms} />
                  </p>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

type HighlightProps = {
  text: string;
  terms: string[];
};

function Highlight({ text, terms }: HighlightProps) {
  if (terms.length === 0) {
    return text;
  }
  const escaped = terms.map((term) => term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const lowerTerms = new Set(terms.map((term) => term.toLowerCase()));
  const parts = text.split(new RegExp(`(${escaped.join('|')})`, 'gi'));
  return (
    <>
      {parts.map((part, index) =>
        lowerTerms.has(part.toLowerCase()) ? <mark key={`${part}-${index}`}>{part}</mark> : <span key={`${part}-${index}`}>{part}</span>
      )}
    </>
  );
}
