export const gestionnairesPerCity: Record<string, { network?: string; gestionnaires: string[] }> = {
  Amiens: { gestionnaires: ['ENGIE'] },
  Antony: { gestionnaires: ['ENGIE_Antony'] },
  Arcueil: { gestionnaires: ['SIPPEREC', 'ENGIE_IDF', 'ENGIE', 'ARGEO'] },
  Argenteuil: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Aubervilliers: {
    gestionnaires: ['SMIREC', 'ENGIE', 'ENGIE_IDF', 'ENGIE_Aubervilliers'],
  },
  Bagneux: { gestionnaires: ['SIPPEREC', 'Dalkia', 'Dalkia_IDF', 'BAGEOPS'] },
  Bagnolet: { gestionnaires: ['ALEC_MVE', 'ENGIE_Bagnolet'] },
  Bobigny: { gestionnaires: ['SIPPEREC', 'ALEC_MVE'] },
  Bondy: { gestionnaires: ['ALEC_MVE'] },
  Bordeaux: { gestionnaires: ['BordeauxM'] },
  'Boulogne-Billancourt': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  'Bourgoin-Jallieu': { gestionnaires: ['Dalkia', 'Dalkia_Bourgoin-Jallieu'] },
  Brest: { gestionnaires: ['BrestM'] },
  Briey: { gestionnaires: ['Dalkia', 'Dalkia_Briey'] },
  'Brive-la-Gaillarde': {
    gestionnaires: ['Coriance_ Brive-la-Gaillarde', 'Coriance'],
  },
  Bron: { gestionnaires: ['LyonM'] },
  Bruges: { gestionnaires: ['BordeauxM'] },
  'Bry-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  'Bussy-Saint-Georges': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  Cachan: { gestionnaires: ['SOCACHAL', 'Dalkia', 'Dalkia_IDF'] },
  'Carrières sur Seine': { gestionnaires: ['ENGIE_Carrieres-sur-Seine'] },
  'Carrières-sous-Poissy': {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'],
  },
  'Champigny-sur-Marne': { gestionnaires: ['EPCampinoisGeoth', 'ALEC_MVE'] },
  'Champs-sur-Marne': {
    gestionnaires: ['ENGIE_IDF', 'ENGIE', 'ENGIE_Champs-sur-Marne'],
  },
  'Charenton-le-Pont': { gestionnaires: ['ALEC_MVE'] },
  'Châtenay-Malabry': { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Châtillon: { gestionnaires: ['SIPPEREC', 'Dalkia', 'BAGEOPS', 'Dalkia_IDF'] },
  Chatou: { gestionnaires: ['ENGIE_Chatou'] },
  'Choisy-le-Roi': {
    gestionnaires: ['SICUCV', 'ENGIE_IDF', 'ENGIE', 'ENGIE_Choisy-le-Roi'],
  },
  Clichy: { gestionnaires: ['IDEX_IDF', 'IDEX'] },
  'Clichy-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  Compiègne: { gestionnaires: ['ENGIE_Compiegne'] },
  Coubron: { gestionnaires: ['ALEC_MVE'] },
  Courbevoie: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Créteil: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  'Dammarie-les-Lys': { gestionnaires: ['ENGIE_Dammarie-les-Lys'] },
  Dijon: { gestionnaires: ['DijonM'] },
  'Épinay-sous-Sénart': { gestionnaires: ['SEMGEP'] },
  Ermont: { gestionnaires: ['ENGIE_Ermont'] },
  'Fontenay-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  Franconville: { network: '9507C', gestionnaires: ['ENGIE_Franconville'] },
  Gagny: { gestionnaires: ['ALEC_MVE'] },
  Gennevilliers: {
    gestionnaires: ['ENGIE_IDF', 'ENGIE', 'ENGIE_Gennevilliers'],
  },
  Gentilly: {
    gestionnaires: ['SIPPEREC', 'ENGIE', 'ENGIE_IDF', 'ARGEO', 'ENGIE_ARGEO'],
  },
  'Gournay-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Grenoble: { gestionnaires: ['GrenobleM'] },
  Grigny: { gestionnaires: ['ENGIE_Grigny'] },
  Houilles: { gestionnaires: ['ENGIE_Houilles'] },
  'Ivry-sur-Seine': { gestionnaires: ['ENGIE_Ivry-sur-Seine'] },
  'Joinville-le-Pont': { gestionnaires: ['ALEC_MVE'] },
  'L’île-Saint-Denis': { gestionnaires: ['ENGIE_LIle-Saint-Denis'] },
  'Le Chesnay-Rocquencourt': { gestionnaires: ['ENGIE_Le-Chesnay'] },
  'Le Perreux-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  'Le Pré-Saint-Gervais': { gestionnaires: ['ALEC_MVE'] },
  'Le Raincy': { gestionnaires: ['ALEC_MVE'] },
  'les Lilas': { gestionnaires: ['ALEC_MVE'] },
  'Les Pavillons-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  'Levallois-Perret': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  Liévin: { gestionnaires: ['Dalkia', 'Lievin'] },
  Lille: { gestionnaires: ['LilleM'] },
  'Limeil-Brévannes': { gestionnaires: ['ENGIE', 'ENGIE_IDF'] },
  Limoges: { gestionnaires: ['LimogesM'] },
  Lisieux: { gestionnaires: ['ENGIE'] },
  'Livry-Gargan': { gestionnaires: ['ALEC_MVE'] },
  Lyon: { gestionnaires: ['LyonM'] },
  Madeleine: { gestionnaires: ['Dalkia'] },
  'Maisons-Alfort': { gestionnaires: ['ALEC_MVE'] },
  'Mantes-la-Jolie': { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'] },
  'Marne-la-Vallée': { gestionnaires: ['ENGIE_Marne-la-Vallee'] },
  Massy: { gestionnaires: ['ENGIE_Massy'] },
  Mérignac: { gestionnaires: ['BordeauxM'] },
  Metz: { gestionnaires: ['MetzM'] },
  Meudon: { gestionnaires: ['ENGIE_Meudon'] },
  'Mons-en-Barœul': { gestionnaires: ['LilleM'] },
  Montesson: { gestionnaires: ['ENGIE_Montesson'] },
  Montfermeil: { gestionnaires: ['ALEC_MVE'] },
  Montreuil: {
    gestionnaires: ['ENGIE', 'ENGIE_IDF', 'ALEC_MVE', 'ENGIE_Montreuil'],
  },
  Nancy: { gestionnaires: ['NancyM'] },
  Nantes: { gestionnaires: ['NantesM'] },
  Nemours: { gestionnaires: ['Dalkia_Nemours'] },
  'Neuilly-Plaisance': { gestionnaires: ['ALEC_MVE'] },
  'Neuilly-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Nice: { gestionnaires: ['NiceM'] },
  Nîmes: { gestionnaires: ['Dalkia'] },
  Noisiel: { gestionnaires: ['ENGIE_Noisiel'] },
  'Noisy-le-Grand': { gestionnaires: ['ALEC_MVE'] },
  'Noisy-le-Sec': {
    gestionnaires: ['SIPPEREC', 'YGEO', 'ENGIE_IDF', 'ENGIE', 'ALEC_MVE', 'ENGIE_Noisy-le-Sec'],
  },
  Pantin: { gestionnaires: ['SIPPEREC', 'ALEC_MVE'] },
  Paris: { gestionnaires: ['CPCU', 'APC'] },
  Pau: { gestionnaires: ['PauM'] },
  'Pierrefitte-sur-Seine': {
    network: '9301C',
    gestionnaires: ['ENGIE_Pierrefitte-sur-Seine'],
  },
  Plaisir: {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78', 'Dalkia_Plaisir'],
  },
  Puteaux: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Reims: { gestionnaires: ['ENGIE_Reims'] },
  Rennes: { gestionnaires: ['RennesM'] },
  Romainville: { gestionnaires: ['ALEC_MVE'] },
  'Rosny-sous-Bois': {
    gestionnaires: ['SIPPEREC', 'ENGIE_IDF', 'ENGIE', 'YGEO', 'ALEC_MVE', 'ENGIE_Rosny-sous-Bois'],
  },
  Roubaix: { gestionnaires: ['LilleM'] },
  Rouen: { gestionnaires: ['RouenM'] },
  'Rueil Malmaison': { gestionnaires: ['ENGIE_Rueil-Malmaison'] },
  'Saint-Denis': {
    gestionnaires: ['ENGIE', 'ENGIE_IDF', 'SMIREC', 'ENGIE_Saint-Denis'],
  },
  'Saint-Étienne': { gestionnaires: ['Saint-EtienneM'] },
  'Saint-Germain-en-Laye': {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'],
  },
  'Saint-Mandé': { gestionnaires: ['ALEC_MVE'] },
  'Saint-Maur-des-Fossés': { gestionnaires: ['ALEC_MVE'] },
  'Saint-Maurice': { gestionnaires: ['ALEC_MVE'] },
  'Sainte-Savine': { gestionnaires: ['TroyesM'] },
  Sannois: { gestionnaires: ['ENGIE_Sannois'] },
  Sarcelles: { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_Sarcelles'] },
  Sartrouville: { gestionnaires: ['ENGIE_Sartrouville'] },
  Schiltigheim: { gestionnaires: ['ENGIE'] },
  Stains: { gestionnaires: ['ENGIE_Stains'] },
  Strasbourg: { gestionnaires: ['StrasbourgM'] },
  'Sucy-en-Brie': { gestionnaires: ['ENGIE_Sucy-en-Brie'] },
  Suresnes: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Thiais: { gestionnaires: ['ENGIE_Thiais'] },
  Toulouse: { gestionnaires: ['ToulouseM'] },
  Valenton: { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_Valenton'] },
  Vaujours: { gestionnaires: ['ALEC_MVE'] },
  'Vaulx-en-Velin': { gestionnaires: ['LyonM'] },
  'Vaux-le-Pénil': { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  'Vélizy-Villacoublay': { gestionnaires: ['ENGIE_Velizy'] },
  Versailles: { gestionnaires: ['ENGIE_Versailles'] },
  Villejuif: { gestionnaires: ['SEMHACH'] },
  Villemomble: { gestionnaires: ['ALEC_MVE'] },
  Villepinte: { gestionnaires: ['ENGIE_Villepinte'] },
  'Villiers-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Vincennes: { gestionnaires: ['ALEC_MVE'] },
  'Vitry-sur-Seine': { gestionnaires: ['ENGIE_Vitry-sur-Seine'] },
  Voreppe: { gestionnaires: ['Dalkia', 'Dalkia_Voreppe'] },
};

export const gestionnairesPerNetwork: Record<string, string[]> = {
  '0101C': ['Dalkia_centre-est'],
  '0105C': ['Dalkia_centre-est', 'Dalkia_0105C', 'Dalkia'],
  '0106C': ['Dalkia_centre-est', 'Dalkia_Belley', 'Dalkia_0106C', 'Dalkia'],
  '0110C': ['ENGIE', 'ENGIE_Bourg-en-Bresse'],
  '0205C': ['Dalkia_0205C', 'Dalkia'],
  '0302C': ['Dalkia_centre-est', 'Dalkia_0302C', 'Dalkia'],
  '0307C': ['Dalkia_centre-est', 'Dalkia_0307C', 'Dalkia'],
  '0406C': ['Dalkia_0406C', 'Dalkia'],
  '0601C': ['NiceM', 'Dalkia_Nice', 'Dalkia'],
  '0602C': ['Dalkia_0602C', 'Dalkia'],
  '0603C': ['Dalkia_0603C', 'Dalkia'],
  '0608C': ['Dalkia_0608C', 'Dalkia'],
  '0609C': ['Dalkia_0609C', 'Dalkia'],
  '0702C': ['Dalkia_centre-est', 'Dalkia_LeCheylard', 'Dalkia_0702C', 'Dalkia'],
  '0802C': ['CU_Charleville-Mezieres', 'Ardenne_Metropole', 'Dalkia', 'Dalkia_0802C'],
  '0803C': ['Dalkia_0803C', 'Dalkia'],
  '0806C': ['Dalkia_0806C', 'Dalkia'],
  '1101C': ['Dalkia_1101C', 'Dalkia'],
  '1207C': ['Pouzols'],
  '1311C': ['Dalkia_1311C', 'Dalkia'],
  '1315C': ['Dalkia_1315C', 'Dalkia'],
  '1317C': ['ENGIE', 'ENGIE_Aix-en-Provence'],
  '1319C': ['ENGIE_Marseille', 'ENGIE'],
  '1322C': ['Dalkia_1322C', 'Dalkia'],
  '1402C': ['ENGIE', 'Dalkia_1402C', 'Dalkia'],
  '1403C': ['Dalkia_1403C', 'Dalkia'],
  '1405C': ['Dalkia_1405C', 'Dalkia'],
  '1406C': ['Dalkia_1406C', 'Dalkia'],
  '1408C': ['CaenM'],
  '1413C': ['CaenM', 'Dalkia', 'Dalkia_1413C'],
  '1702C': ['Dalkia_1702C', 'Dalkia'],
  '1703C': ['Dalkia_1703C', 'Dalkia'],
  '1704C': ['Dalkia_1704C', 'Dalkia'],
  '1705C': ['Dalkia_1705C', 'Dalkia'],
  '1903C': ['Dalkia_1903C', 'Dalkia'],
  '1909C': ['Dalkia_1909C', 'Dalkia'],
  '2102C': ['DijonM', 'Coriance', 'Coriance_Dijon'],
  '2106C': ['Dalkia_centre-est', 'DijonM', 'Dalkia', 'Dalkia_Dijon', 'Dalkia_2106C'],
  '2502C': ['Dalkia_2502C', 'Dalkia'],
  '2604C': ['Dalkia_centre-est', 'Dalkia_Montelimar_Pracomtal', 'Dalkia_2604C', 'Dalkia'],
  '2701C': ['Dalkia', 'Dalkia_2701C'],
  '2702C': ['Dalkia_2702C', 'Dalkia'],
  '2703C': ['Dalkia_2703C', 'Dalkia'],
  '2705C': ['Dalkia_2705C', 'Dalkia'],
  '2802C': ['Dalkia_2802C', 'Dalkia'],
  '2901C': ['BrestM', 'Dalkia', 'Dalkia_Brest'],
  '3001C': ['MontpellierM', 'Dalkia', 'Dalkia_3001C'],
  '3002C': ['Dalkia_3002C', 'Dalkia'],
  '3101C': ['ToulouseM', 'Coriance_Toulouse', 'Coriance'],
  '3106C': ['ToulouseM', 'Dalkia', 'Dalkia_Toulouse', 'Dalkia_3106C'],
  '3112C': ['Dalkia_3112C', 'Dalkia'],
  '3302C': ['BordeauxM', 'Engie_Bordeaux', 'ENGIE'],
  '3303C': ['BordeauxM'],
  '3304C': ['BordeauxM', 'Mixener', 'IDEX', 'Dalkia_3304C', 'Dalkia'],
  '3306C': ['Mixener', 'BordeauxM', 'IDEX'],
  '3315C': ['BordeauxM', 'Dalkia_3315C', 'Dalkia'],
  '3316C': ['BordeauxM'],
  '3317C': ['BordeauxM'],
  '3318C': ['BordeauxM', 'Mixener', 'IDEX'],
  '3319C': ['BordeauxM', 'Mixener', 'IDEX'],
  '3324C': ['BordeauxM', 'IDEX', 'Mixener'],
  '3410C': ['SERM_Montpellier', 'MontpellierM'],
  '3412C': ['Dalkia_3412C', 'Dalkia'],
  '3506C': ['RennesM', 'RennesM_Rennes Sud', 'ENGIE', 'Engie_Rennes'],
  '3507C': ['RennesM', 'Engie_Rennes', 'ENGIE', 'EnRnov_Rennes'],
  '3605C': ['Dalkia_3605C', 'Dalkia'],
  '3702C': ['Dalkia', 'Dalkia_Tours', 'Dalkia_3702C'],
  '3712C': ['ENGIE', 'ENGIE_Tours'],
  '3802C': ['GrenobleM', 'CCIAG_Grenoble'],
  '3803C': ['Dalkia_centre-est', 'Dalkia', 'Dalkia_Bourgoin-Jallieu', 'Dalkia_Bourgouin-Jallieu', 'Dalkia_3803C'],
  '3806C': ['Dalkia_centre-est', 'Dalkia', 'Dalkia_Allevard', 'Dalkia_3806C'],
  '3813C': ['Dalkia_centre-est', 'Dalkia', 'Dalkia_Voreppe', 'Dalkia_3813C'],
  '3814C': ['Dalkia_centre-est', 'Dalkia_3814C', 'Dalkia'],
  '4101C': ['ENGIE', 'ENGIE_Blois'],
  '4102C': ['Dalkia_4102C', 'Dalkia'],
  '4106C': ['Dalkia_4106C', 'Dalkia'],
  '4202C': ['Dalkia_centre-est', 'Saint-EtienneM', 'Dalkia_4202C', 'Dalkia'],
  '4204C': ['Dalkia_centre-est', 'Saint-EtienneM', 'Dalkia', 'Dalkia_Saint-Etienne', 'Dalkia_4204C'],
  '4206C': ['Saint-EtienneM'],
  '4207C': ['Dalkia_centre-est', 'Dalkia_4207C', 'Dalkia'],
  '4208C': ['Dalkia_4208C', 'Dalkia'],
  '4210C': ['Dalkia_centre-est', 'Saint-EtienneM', 'Dalkia_Saint-Etienne-Montreynaud', 'Dalkia', 'Dalkia_4210C'],
  '4214C': ['Dalkia_centre-est', 'Saint-EtienneM', 'Dalkia_4214C', 'Dalkia'],
  '4247C': ['Saint-EtienneM'],
  '4405C': ['NantesM', 'Dalkia', 'Dalkia_Nantes', 'Dalkia_4405C'],
  '4501C': ['Dalkia_4501C', 'Dalkia'],
  '4503C': ['OrléansM', 'ENGIE_Orleans', 'ENGIE'],
  '4504C': ['Dalkia', 'Dalkia_Montargis', 'Dalkia_4504C'],
  '4505C': ['Dalkia_4505C', 'Dalkia'],
  '4507C': ['Dalkia_4507C', 'Dalkia'],
  '4802C': ['Dalkia_4802C', 'Dalkia'],
  '4901C': ['AngersM'],
  '4902C': ['Dalkia_4902C', 'Dalkia'],
  '4907C': ['AngersM', 'ALTER', 'Dalkia', 'Dalkia_Angers'],
  '4911C': ['AngersM', 'ALTER'],
  '5002C': ['Dalkia_5002C', 'Dalkia'],
  '5101C': ['Dalkia_5101C', 'Dalkia'],
  '5103C': ['Dalkia_5103C', 'Dalkia'],
  '5108C': ['Dalkia_5108C', 'Dalkia'],
  '5401C': ['NancyM', 'Dalkia', 'Dalkia_Nancy', 'Dalkia_5401C'],
  '5403C': ['NancyM', 'Dalkia', 'Dalkia_Nancy', 'Dalkia_5403C'],
  '5407C': ['Dalkia', 'Dalkia_Nancy', 'NancyM', 'Dalkia_5407C'],
  '5410C': ['Dalkia_5410C', 'Dalkia'],
  '5411C': ['NancyM', 'Dalkia_Nancy', 'Dalkia', 'Dalkia_5411C'],
  '5413C': ['Dalkia_5413C', 'Dalkia'],
  '5414C': ['MetzM', 'Briey', 'Dalkia', 'Dalkia_Briey', 'Dalkia_5414C'],
  '5502C': ['Dalkia', 'Dalkia_Nord_Lorraine', 'Dalkia_5502C'],
  '5503C': ['Dalkia_5503C', 'Dalkia'],
  '5601C': ['Dalkia_5601C', 'Dalkia'],
  '5701C': ['MetzM'],
  '5706C': ['ENGIE', 'Dalkia_5706C', 'Dalkia'],
  '5707C': ['Dalkia_5707C', 'Dalkia'],
  '5802C': ['Dalkia_centre-est', 'Dalkia_5802C', 'Dalkia'],
  '5803C': ['Dalkia_centre-est', 'Dalkia_5803C', 'Dalkia'],
  '5901C': ['LilleM', 'Dalkia', 'Dalkia_Roubaix', 'Dalkia_Lille', 'Dalkia_5901C'],
  '5904C': ['Dalkia_5904C', 'Dalkia'],
  '5905C': ['LilleM', 'Dalkia_5905C', 'Dalkia'],
  '5906C': ['LilleM', 'Dalkia_5906C', 'Dalkia'],
  '5907C': ['LilleM', 'Dalkia_5907C', 'Dalkia'],
  '5908C': ['Dalkia_5908C', 'Dalkia'],
  '5909C': ['LilleM', 'Dalkia_5909C', 'Dalkia'],
  '5910C': ['LilleM', 'Dalkia_Lille', 'Dalkia', 'Madeleine', 'Dalkia_5910C'],
  '5912C': ['Dalkia_5912C', 'Dalkia'],
  '5914C': ['Dalkia_5914C', 'Dalkia'],
  '5916C': ['Dalkia_5916C', 'Dalkia'],
  '5917C': ['LilleM', 'Dalkia_5917C', 'Dalkia'],
  '5922C': ['Dalkia_5922C', 'Dalkia'],
  '6002C': ['Dalkia_6002C', 'Dalkia'],
  '6003C': ['Dalkia_6003C', 'Dalkia'],
  '6004C': ['Dalkia_6004C', 'Dalkia'],
  '6006C': ['Dalkia_6006C', 'Dalkia'],
  '6103C': ['Dalkia_6103C', 'Dalkia'],
  '6104C': ['Dalkia_6104C', 'Dalkia'],
  '6109C': ['Dalkia_Alencon', 'Dalkia', 'Dalkia_6109C'],
  '6201C': ['Dalkia', 'Dalkia_Avion', 'Dalkia_6201C'],
  '6203C': ['Dalkia_6203C', 'Dalkia'],
  '6204C': ['Dalkia', 'Dalkia_Bethune', 'Dalkia_6204C'],
  '6206C': ['Dalkia', 'Dalkia_Lievin', 'Dalkia_6206C'],
  '6209C': ['Dalkia_6209C', 'Dalkia'],
  '6210C': ['Dalkia_6210C', 'Dalkia'],
  '6211C': ['Dalkia_6211C', 'Dalkia'],
  '6212C': ['Dalkia_6212C', 'Dalkia'],
  '6304C': ['Dalkia_centre-est', 'Dalkia_6304C', 'Dalkia'],
  '6306C': ['Dalkia_centre-est', 'Clermont-FerrandM', 'Dalkia', 'Dalkia_6306C'],
  '6307C': ['Dalkia_centre-est', 'Clermont-FerrandM', 'Dalkia_6307C', 'Dalkia'],
  '6402C': ['Dalkia_6402C', 'Dalkia'],
  '6501C': ['Dalkia_6501C', 'Dalkia'],
  '6604C': ['Dalkia_6604C', 'Dalkia'],
  '6701C': ['StrasbourgM', 'Strasbourg_centre_energie'],
  '6725C': ['StrasbourgM', 'Strasbourg_Wacken', 'R-CUA'],
  '6728C': ['StrasbourgM'],
  '6801C': ['SCCU_Colmar'],
  '6901C': ['Dalkia_centre-est', 'LyonM', 'Dalkia', 'Dalkia_ELM Lyon', 'Dalkia_Venissieux', 'Dalkia_6901C'],
  '6902C': ['Dalkia_Lyon_ouest'],
  '6904C': ['Dalkia_centre-est', 'Dalkia_6904C', 'Dalkia'],
  '6905C': ['Dalkia_centre-est', 'LyonM', 'Dalkia', 'Dalkia_ELM Lyon', 'Dalkia_Venissieux', 'Dalkia_6905C'],
  '6905F': ['LyonM', 'Dalkia', 'Dalkia_ELM Lyon'],
  '6906C': ['Dalkia_centre-est', 'Dalkia_6906C', 'Dalkia'],
  '6912C': ['IDEX', 'LyonM', 'IDEX_Givors'],
  '6913C': ['Sytraival'],
  '6915C': ['Dalkia_6915C', 'Dalkia'],
  '6918C': ['Dalkia_centre-est', 'Dalkia_6918C', 'Dalkia'],
  '6930C': ['LyonM', 'Engie_Lyon', 'ENGIE'],
  '7104C': ['Dalkia_centre-est', 'Dalkia_7104C', 'Dalkia'],
  '7301C': ['ENGIE_Chambery', 'ENGIE'],
  '7318C': ['Dalkia_centre-est', 'Dalkia_Ugine', 'Dalkia_7318C', 'Dalkia'],
  '7319C': ['Dalkia_centre-est', 'Dalkia_Albertville', 'Dalkia_7319C', 'Dalkia'],
  '7402C': ['Dalkia_centre-est', 'Dalkia', 'Dalkia_Annecy', 'Dalkia_7402C'],
  '7407C': ['Dalkia_centre-est', 'Dalkia_7407C', 'Dalkia'],
  '7408C': ['Dalkia_centre-est', 'Dalkia_Cluses', 'Dalkia_7408C', 'Dalkia'],
  '7410C': ['Dalkia_centre-est', 'Dalkia_Faverges', 'Dalkia_7410C', 'Dalkia'],
  '7411C': ['Dalkia_centre-est', 'Dalkia_7411C', 'Dalkia'],
  '7412C': ['Dalkia_centre-est', 'Dalkia_7412C', 'Dalkia'],
  '7421C': ['IDEX', 'Idex_Annecy'],
  '7423C': ['Dalkia_centre-est', 'Dalkia_Reignier', 'Dalkia_7423C', 'Dalkia'],
  '7501C': ['CPCU', 'APC', 'Paris'],
  '7601C': ['RouenM', 'Dalkia_7601C', 'Dalkia'],
  '7602C': ['LeHavreM'],
  '7603C': ['LeHavreM', 'Dalkia_7603C', 'Dalkia'],
  '7605C': ['RouenM', 'Coriance_Rouen', 'Coriance'],
  '7606C': ['Dalkia_7606C', 'Dalkia'],
  '7607C': ['RouenM'],
  '7609C': ['Dalkia_7609C', 'Dalkia'],
  '7612C': ['RouenM', 'Dalkia_7612C', 'Dalkia'],
  '7613C': ['LeHavreM', 'Dalkia_7613C', 'Dalkia'],
  '7614C': ['RouenM', 'Dalkia_Rouen-Grammont', 'Dalkia', 'Dalkia_7614C'],
  '7616C': ['SRBG'],
  '7701C': ['Coriance', 'Coriance_IDF'],
  '7703C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_7703C'],
  '7705C': ['Dalkia_7705C', 'Dalkia'],
  '7707C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_7707C'],
  '7710C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_7710C'],
  '7711C': ['Dalkia_7711C', 'Dalkia'],
  '7716C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_7716C'],
  '7717C': ['Coriance', 'Coriance_IDF'],
  '7721C': ['Dalkia_7721C', 'Dalkia'],
  '7724C': ['IDEX', 'IDEX_IDF', 'IDEX_Bussy-Saint-Georges'],
  '7727C': ['ALEC_MVE'],
  '7802C': ['Dalkia_78', 'Dalkia', 'Dalkia_7802C'],
  '7803C': ['ENGIE_Versailles', 'ENGIE', 'ENGIE_IDF'],
  '7804C': ['ENGIE_IDF', 'ENGIE', 'ENGIE_Le-Chesnay'],
  '7805C': ['Dalkia', 'Dalkia_IDF', 'DDT78', 'Dalkia_78', 'Dalkia_7805C'],
  '7807C': ['Dalkia_7807C', 'Dalkia'],
  '7811C': ['ENGIE_Sartrouville', 'ENGIE', 'ENGIE_IDF', 'ENGIE_78', 'DDT78', 'ENGIE_Chatou'],
  '7812C': ['DDT78', 'Dalkia', 'Dalkia_IDF', 'Dalkia_78', 'Dalkia_Plaisir', 'ALEC_SQY', 'Dalkia_7812C'],
  '7816C': ['Dalkia_7816C', 'Dalkia'],
  '7901C': ['Dalkia_7901C', 'Dalkia'],
  '8005C': ['Dalkia_8005C', 'Dalkia'],
  '8102C': ['Dalkia_8102C', 'Dalkia'],
  '8307C': ['Dalkia_8307C', 'Dalkia'],
  '8401C': ['Dalkia_8401C', 'Dalkia'],
  '8502C': ['Dalkia_8502C', 'Dalkia'],
  '8601C': ['Dalkia_8601C', 'Dalkia'],
  '8607C': ['Dalkia_8607C', 'Dalkia'],
  '8701C': ['LimogesM', 'Dalkia_8701C', 'Dalkia'],
  '8702C': ['Dalkia_8702C', 'Dalkia'],
  '8802C': ['Dalkia_8802C', 'Dalkia'],
  '9002C': ['Dalkia_9002C', 'Dalkia'],
  '9101C': ['ENGIE', 'ENGIE_IDF', 'ENGIE_Massy'],
  '9102C': ['Dalkia_9102C', 'Dalkia'],
  '9103C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_Grand-Paris-Sud', 'Dalkia_9103C'],
  '9104C': ['SIPPEREC', 'SIPPEREC_SEER', 'SEER', 'ENGIE_Grigny', 'ENGIE_IDF', 'ENGIE'],
  '9107C': ['IDEX', 'IDEX_IDF', 'IDEX_Dourdan'],
  '9109C': ['IDEX', 'IDEX_IDF', 'IDEX_Vigneux-sur-Seine'],
  '9114C': ['SEMGEP'],
  '9119C': ['Dalkia_9119C', 'Dalkia'],
  '9120C': ['Dalkia_9120C', 'Dalkia'],
  '9121C': ['Dalkia_9121C', 'Dalkia'],
  '9125C': ['Dalkia_9125C', 'Dalkia'],
  '9205C': ['ENGIE_IDF', 'ENGIE', 'ENGIE_Gennevilliers'],
  '9209C': ['ENGIE', 'ENGIE_Chaville', 'ENGIE_IDF'],
  '9211C': ['IDEX', 'IDEX_IDF', 'IDEX_Levallois-Perret'],
  '9219C': ['IDEX', 'IDEX_IDF', 'IDEX_Boulogne-Billancourt'],
  '9222C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_9222C'],
  '9224C': ['Dalkia', 'Dalkia_IDF', 'Courbevoie', 'Dalkia_9224C'],
  '9225C': ['IDEX', 'IDEX_IDF', 'IDEX_La Défense'],
  '9230C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_9230C'],
  '9233C': ['Dalkia_9233C', 'Dalkia'],
  '9234C': ['Dalkia_9234C', 'Dalkia'],
  '9235C': ['IDEX_IDF', 'IDEX', 'IDEX_Clichy-la-Garenne'],
  '9236C': ['SIPPEREC', 'Dalkia', 'Dalkia_IDF', 'BAGEOPS', 'Dalkia_9236C'],
  '9301C': ['ENGIE', 'ENGIE_IDF', 'SMIREC', 'ENGIE_Saint-Denis', 'ENGIE_Aubervilliers', 'ENGIE_Stains'],
  '9302C': ['ALEC_MVE', 'ENGIE_Bagnolet', 'ENGIE', 'ENGIE_IDF', 'SDCB', 'SIPPEREC', 'ENGIE_Montreuil'],
  '9303C': ['SIPPEREC', 'GENYO', 'ALEC_MVE', 'YGEO', 'ENGIE_IDF', 'ENGIE', 'ENGIE_Noisy-le-Sec'],
  '9304C': ['ENGIE_Sevran', 'ENGIE', 'ENGIE_IDF'],
  '9305C': ['ALEC_MVE', 'IDEX_Neuilly-sur-Marne', 'IDEX_IDF', 'IDEX'],
  '9309C': ['Dalkia_9309C', 'Dalkia'],
  '9310C': ['Blanc-Mesnil'],
  '9311C': ['ALEC_MVE', 'Dalkia', 'Dalkia_IDF', 'Dalkia_9311C'],
  '9314C': ['IDEX', 'IDEX_IDF', 'IDEX_Tremblay-en-France'],
  '9316C': ['ALEC_MVE', 'Coriance', 'Coriance_IDF'],
  '9317C': ['Dalkia_9317C', 'Dalkia'],
  '9324C': ['ENGIE', 'ENGIE_IDF', 'ALEC_MVE', 'ENGIE_Montreuil', 'SIPPEREC', 'YGEO', 'ENGIE_Noisy-le-Sec', 'ENGIE_Rosny-sous-Bois'],
  '9401C': ['ENGIE', 'ENGIE_IDF', 'ENGIE_Limeil-Brevannes'],
  '9402C': ['Dalkia', 'Dalkia_IDF', 'ALEC_MVE', 'Dalkia_9402C'],
  '9403C': ['ENGIE_Vitry-sur-Seine', 'SICUCV', 'ENGIE', 'ENGIE_IDF', 'ENGIE_Choisy-le-Roi'],
  '9404C': ['ALEC_MVE'],
  '9408C': ['AGESVAM'],
  '9409C': ['ENGIE_Sucy-en-Brie', 'ENGIE_IDF', 'ENGIE'],
  '9410C': ['SOCACHAL', 'Dalkia', 'Dalkia_IDF', 'Dalkia_9410C'],
  '9411C': ['ALEC_MVE', 'EPCampinoisGeoth'],
  '9412C': ['ALEC_MVE', 'SEMGEMA'],
  '9413C': ['ENGIE', 'ENGIE_IDF', 'ENGIE_Choisy-le-Roi', 'ENGIE_Thiais'],
  '9415C': ['SEMHACH'],
  '9419C': ['Coriance', 'Coriance_IDF', 'ENGIE_Antony'],
  '9420C': ['AGESVAM'],
  '9422C': ['SIPPEREC', 'ENGIE', 'ENGIE_IDF', 'ARGEO', 'ENGIE_ARGEO'],
  '9423C': ['ENGIE_Ivry-sur-Seine', 'ENGIE', 'ENGIE_IDF'],
  '9424C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_Valenton', 'Dalkia_9424C'],
  '9430C': ['Dalkia_9430C', 'Dalkia'],
  '9502C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_Sarcelles', 'Dalkia_9502C'],
  '9503C': ['Coriance_IDF', 'Coriance'],
  '9505C': ['Coriance', 'Coriance_IDF'],
  '9507C': ['ENGIE', 'ENGIE_IDF', 'ENGIE_Franconville'],
  '9509C': ['Dalkia', 'Dalkia_IDF', 'Dalkia_Argenteuil', 'Dalkia_Bezons', 'Dalkia_9509C'],
  '9514C': ['Coriance', 'Coriance_IDF'],
  '9515C': ['Dalkia', 'Dalkia_IDF'],
  '9516C': ['Dalkia_9516C', 'Dalkia'],
  '9518C': ['Dalkia_9518C', 'Dalkia'],
  '9520C': ['Dalkia_9520C', 'Dalkia'],
};

export const gestionnairesPerDepartment: Record<string, string[]> = {
  'Puy-de-Dôme': ['ADUHME'],
};
