export const gestionnaires: Record<
  string,
  { network?: string; gestionnaires: string[] }
> = {
  Amiens: { gestionnaires: ['ENGIE'] },
  Angers: { gestionnaires: ['Dalkia', 'Dalkia_Angers'] },
  Annecy: { gestionnaires: ['IDEX', 'Idex_Annecy'] },
  Antony: { gestionnaires: ['ENGIE_Antony'] },
  Arcueil: { gestionnaires: ['SIPPEREC', 'ENGIE_IDF', 'ENGIE', 'ARGEO'] },
  Argenteuil: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Aubervilliers: {
    gestionnaires: ['SMIREC', 'ENGIE', 'ENGIE_IDF', 'ENGIE_Aubervilliers'],
  },
  Bagneux: { gestionnaires: ['SIPPEREC', 'Dalkia', 'Dalkia_IDF', 'BAGEOPS'] },
  Bagnolet: { gestionnaires: ['ALEC_MVE', 'ENGIE_Bagnolet'] },
  Bobigny: { gestionnaires: ['SIPPEREC', 'ALEC_MVE'] },
  Bondy: { gestionnaires: ['ALEC_MVE'] },
  Bordeaux: { gestionnaires: ['BordeauxM'] },
  'Boulogne-Billancourt': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  'Bourgoin-Jallieu': { gestionnaires: ['Dalkia', 'Dalkia_Bourgoin-Jallieu'] },
  Brest: { gestionnaires: ['BrestM'] },
  Briey: { gestionnaires: ['Dalkia', 'Dalkia_Briey'] },
  'Brive-la-Gaillarde': {
    gestionnaires: ['Coriance_ Brive-la-Gaillarde', 'Coriance'],
  },
  Bron: { gestionnaires: ['LyonM'] },
  Bruges: { gestionnaires: ['BordeauxM'] },
  'Bry-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  'Bussy-Saint-Georges': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  Cachan: { gestionnaires: ['SOCACHAL', 'Dalkia', 'Dalkia_IDF'] },
  'Carrières sur Seine': { gestionnaires: ['ENGIE_Carrieres-sur-Seine'] },
  'Carrières-sous-Poissy': {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'],
  },
  'Champigny-sur-Marne': { gestionnaires: ['EPCampinoisGeoth', 'ALEC_MVE'] },
  'Champs-sur-Marne': {
    gestionnaires: ['ENGIE_IDF', 'ENGIE', 'ENGIE_Champs-sur-Marne'],
  },
  'Charenton-le-Pont': { gestionnaires: ['ALEC_MVE'] },
  'Châtenay-Malabry': { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Châtillon: { gestionnaires: ['SIPPEREC', 'Dalkia', 'BAGEOPS', 'Dalkia_IDF'] },
  Chatou: { gestionnaires: ['ENGIE_Chatou'] },
  'Choisy-le-Roi': {
    gestionnaires: ['SICUCV', 'ENGIE_IDF', 'ENGIE', 'ENGIE_Choisy-le-Roi'],
  },
  Clichy: { gestionnaires: ['IDEX_IDF', 'IDEX', 'IDEX_Clichy-la-Garenne '] },
  'Clichy-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  Compiègne: { gestionnaires: ['ENGIE_Compiegne'] },
  Coubron: { gestionnaires: ['ALEC_MVE'] },
  Courbevoie: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Créteil: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  'Dammarie-les-Lys': { gestionnaires: ['ENGIE_Dammarie-les-Lys'] },
  Dijon: { gestionnaires: ['DijonM'] },
  'Épinay-sous-Sénart': { gestionnaires: ['SEMGEP'] },
  Ermont: { gestionnaires: ['ENGIE_Ermont'] },
  'Fontenay-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  Franconville: { network: '9507C', gestionnaires: ['ENGIE_Franconville'] },
  Gagny: { gestionnaires: ['ALEC_MVE'] },
  Gennevilliers: {
    gestionnaires: ['ENGIE_IDF', 'ENGIE', 'ENGIE_Gennevilliers'],
  },
  Gentilly: {
    gestionnaires: ['SIPPEREC', 'ENGIE', 'ENGIE_IDF', 'ARGEO', 'ENGIE_ARGEO'],
  },
  'Gournay-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Grenoble: { gestionnaires: ['GrenobleM'] },
  Grigny: { gestionnaires: ['ENGIE_Grigny'] },
  Houilles: { gestionnaires: ['ENGIE_Houilles'] },
  'Ivry-sur-Seine': { gestionnaires: ['ENGIE_Ivry-sur-Seine'] },
  'Joinville-le-Pont': { gestionnaires: ['ALEC_MVE'] },
  'L’île-Saint-Denis': { gestionnaires: ['ENGIE_LIle-Saint-Denis'] },
  'Le Chesnay-Rocquencourt': { gestionnaires: ['ENGIE_Le-Chesnay'] },
  'Le Perreux-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  'Le Pré-Saint-Gervais': { gestionnaires: ['ALEC_MVE'] },
  'Le Raincy': { gestionnaires: ['ALEC_MVE'] },
  'les Lilas': { gestionnaires: ['ALEC_MVE'] },
  'Les Pavillons-sous-Bois': { gestionnaires: ['ALEC_MVE'] },
  'Levallois-Perret': { gestionnaires: ['IDEX', 'IDEX_IDF'] },
  Liévin: { gestionnaires: ['Dalkia', 'Lievin'] },
  Lille: { gestionnaires: ['LilleM'] },
  'Limeil-Brévannes': { gestionnaires: ['ENGIE', 'ENGIE_IDF'] },
  Limoges: { gestionnaires: ['LimogesM'] },
  Lisieux: { gestionnaires: ['ENGIE'] },
  'Livry-Gargan': { gestionnaires: ['ALEC_MVE'] },
  Lyon: { gestionnaires: ['LyonM'] },
  Madeleine: { gestionnaires: ['Dalkia'] },
  'Maisons-Alfort': { gestionnaires: ['ALEC_MVE'] },
  'Mantes-la-Jolie': { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'] },
  'Marne-la-Vallée': { gestionnaires: ['ENGIE_Marne-la-Vallee'] },
  Massy: { gestionnaires: ['ENGIE_Massy'] },
  Mérignac: { gestionnaires: ['BordeauxM'] },
  Metz: { gestionnaires: ['MetzM'] },
  Meudon: { gestionnaires: ['ENGIE_Meudon'] },
  'Mons-en-Barœul': { gestionnaires: ['LilleM'] },
  Montesson: { gestionnaires: ['ENGIE_Montesson'] },
  Montfermeil: { gestionnaires: ['ALEC_MVE'] },
  Montreuil: {
    gestionnaires: ['ENGIE', 'ENGIE_IDF', 'ALEC_MVE', 'ENGIE_Montreuil'],
  },
  Nancy: { gestionnaires: ['NancyM'] },
  Nantes: { gestionnaires: ['NantesM'] },
  Nemours: { gestionnaires: ['Dalkia_Nemours'] },
  'Neuilly-Plaisance': { gestionnaires: ['ALEC_MVE'] },
  'Neuilly-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Nice: { gestionnaires: ['NiceM'] },
  Nîmes: { gestionnaires: ['Dalkia'] },
  Noisiel: { gestionnaires: ['ENGIE_Noisiel'] },
  'Noisy-le-Grand': { gestionnaires: ['ALEC_MVE'] },
  'Noisy-le-Sec': {
    gestionnaires: [
      'SIPPEREC',
      'YGEO',
      'ENGIE_IDF',
      'ENGIE',
      'ALEC_MVE',
      'ENGIE_Noisy-le-Sec',
    ],
  },
  Pantin: { gestionnaires: ['SIPPEREC', 'ALEC_MVE'] },
  Paris: { gestionnaires: ['CPCU', 'APC'] },
  Pau: { gestionnaires: ['PauM'] },
  'Pierrefitte-sur-Seine': {
    network: '9301C',
    gestionnaires: ['ENGIE_Pierrefitte-sur-Seine'],
  },
  Plaisir: {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78', 'Dalkia_Plaisir'],
  },
  Puteaux: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Reims: { gestionnaires: ['ENGIE_Reims'] },
  Rennes: { gestionnaires: ['RennesM'] },
  Romainville: { gestionnaires: ['ALEC_MVE'] },
  'Rosny-sous-Bois': {
    gestionnaires: [
      'SIPPEREC',
      'ENGIE_IDF',
      'ENGIE',
      'YGEO',
      'ALEC_MVE',
      'ENGIE_Rosny-sous-Bois',
    ],
  },
  Roubaix: { gestionnaires: ['LilleM'] },
  Rouen: { gestionnaires: ['RouenM'] },
  'Rueil Malmaison': { gestionnaires: ['ENGIE_Rueil-Malmaison'] },
  'Saint-Denis': {
    gestionnaires: ['ENGIE', 'ENGIE_IDF', 'SMIREC', 'ENGIE_Saint-Denis'],
  },
  'Saint-Étienne': { gestionnaires: ['Saint-EtienneM'] },
  'Saint-Germain-en-Laye': {
    gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_78'],
  },
  'Saint-Mandé': { gestionnaires: ['ALEC_MVE'] },
  'Saint-Maur-des-Fossés': { gestionnaires: ['ALEC_MVE'] },
  'Saint-Maurice': { gestionnaires: ['ALEC_MVE'] },
  'Sainte-Savine': { gestionnaires: ['TroyesM'] },
  Sannois: { gestionnaires: ['ENGIE_Sannois'] },
  Sarcelles: { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_Sarcelles'] },
  Sartrouville: { gestionnaires: ['ENGIE_Sartrouville'] },
  Schiltigheim: { gestionnaires: ['ENGIE'] },
  Stains: { gestionnaires: ['ENGIE_Stains'] },
  Strasbourg: { gestionnaires: ['StrasbourgM'] },
  'Sucy-en-Brie': { gestionnaires: ['ENGIE_Sucy-en-Brie'] },
  Suresnes: { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  Thiais: { gestionnaires: ['ENGIE_Thiais'] },
  Toulouse: { gestionnaires: ['ToulouseM'] },
  Valenton: { gestionnaires: ['Dalkia', 'Dalkia_IDF', 'Dalkia_Valenton'] },
  Vaujours: { gestionnaires: ['ALEC_MVE'] },
  'Vaulx-en-Velin': { gestionnaires: ['LyonM'] },
  'Vaux-le-Pénil': { gestionnaires: ['Dalkia', 'Dalkia_IDF'] },
  'Vélizy-Villacoublay': { gestionnaires: ['ENGIE_Velizy'] },
  Versailles: { gestionnaires: ['ENGIE_Versailles'] },
  Villejuif: { gestionnaires: ['SEMHACH'] },
  Villemomble: { gestionnaires: ['ALEC_MVE'] },
  Villepinte: { gestionnaires: ['ENGIE_Villepinte'] },
  'Villiers-sur-Marne': { gestionnaires: ['ALEC_MVE'] },
  Vincennes: { gestionnaires: ['ALEC_MVE'] },
  'Vitry-sur-Seine': { gestionnaires: ['ENGIE_Vitry-sur-Seine'] },
  Voreppe: { gestionnaires: ['Dalkia', 'Dalkia_Voreppe'] },
};
