import db from 'src/db';
import { Network } from 'src/types/Summary/Network';

export const getNetwork = (id: string): Promise<Network> =>
  db('reseaux_de_chaleur')
    .select(
      'Taux EnR&R',
      'Identifiant reseau',
      'has_trace',
      'Gestionnaire',
      'contenu CO2',
      'contenu CO2 ACV',
      'contenu_CO2_2023_tmp',
      'contenu_CO2_ACV_2023_tmp',
      'nom_reseau',
      'Rend%',
      'Dev_reseau%',
      'PM',
      'PM_L',
      'PM_T',
      'PV%',
      'PF%',
      'livraisons_totale_MWh',
      'livraisons_residentiel_MWh',
      'livraisons_tertiaire_MWh',
      'livraisons_industrie_MWh',
      'livraisons_agriculture_MWh',
      'livraisons_autre_MWh',
      'longueur_reseau',
      'nb_pdl',
      'annee_creation',
      'eau_chaude',
      'eau_surchauffee',
      'vapeur',
      'MO',
      'adresse_mo',
      'CP_MO',
      'ville_mo',
      'prod_MWh_gaz_naturel',
      'prod_MWh_charbon',
      'prod_MWh_fioul_domestique',
      'prod_MWh_fioul_lourd',
      'prod_MWh_GPL',
      'prod_MWh_biomasse_solide',
      'prod_MWh_dechets_internes',
      'prod_MWh_UIOM',
      'prod_MWh_biogaz',
      'prod_MWh_geothermie',
      'prod_MWh_PAC',
      'prod_MWh_solaire_thermique',
      'prod_MWh_chaleur_industiel',
      'prod_MWh_autre_chaleur_recuperee',
      'prod_MWh_autres_ENR',
      'prod_MWh_chaudieres_electriques',
      'prod_MWh_autres',
      'production_totale_MWh',
      'puissance_MW_totale',
      'puissance_MW_gaz_naturel',
      'puissance_MW_charbon',
      'puissance_MW_fioul_domestique',
      'puissance_MW_fioul_lourd',
      'puissance_MW_GPL',
      'puissance_MW_biomasse_solide',
      'puissance_MW_dechets_internes',
      'puissance_MW_UIOM',
      'puissance_MW_biogaz',
      'puissance_MW_geothermie',
      'puissance_MW_PAC',
      'puissance_MW_solaire_thermique',
      'puissance_MW_chaleur_industiel',
      'puissance_MW_autre_chaleur_recuperee',
      'puissance_MW_chaudieres_electriques',
      'puissance_MW_autres',
      'puissance_MW_autres_ENR',
      db.raw('ST_X(ST_Transform(ST_Centroid(geom), 4326)) as lon'),
      db.raw('ST_Y(ST_Transform(ST_Centroid(geom), 4326)) as lat'),
      'website_gestionnaire',
      'reseaux classes',
      'informationsComplementaires',
      'fichiers',
      'region'
    )
    .where('Identifiant reseau', id)
    .first();

export const getColdNetwork = (id: string): Promise<Network> =>
  db('reseaux_de_froid')
    .select(
      'Taux EnR&R',
      'Identifiant reseau',
      'Gestionnaire',
      'contenu CO2',
      'contenu CO2 ACV',
      'contenu_CO2_2023_tmp',
      'contenu_CO2_ACV_2023_tmp',
      'nom_reseau',
      'livraisons_totale_MWh',
      'livraisons_residentiel_MWh',
      'livraisons_tertiaire_MWh',
      'livraisons_industrie_MWh',
      'livraisons_agriculture_MWh',
      'livraisons_autre_MWh',
      'production_totale_MWh',
      'puissance_totale_MW as puissance_MW_totale',
      'longueur_reseau',
      'nb_pdl',
      'annee_creation',
      'MO',
      'adresse_mo',
      'CP_MO',
      'ville_mo',
      db.raw('ST_X(ST_Transform(ST_Centroid(geom), 4326)) as lon'),
      db.raw('ST_Y(ST_Transform(ST_Centroid(geom), 4326)) as lat'),
      'website_gestionnaire',
      'informationsComplementaires',
      'fichiers',
      'Rend%'
    )
    .where('Identifiant reseau', id)
    .first();
