export enum Airtable {
  UTILISATEURS = 'FCU - Utilisateurs',
  RELANCE = 'FCU - Utilisateurs relance',
  CONTACT = 'FCU - Formulaire de contact',
  NEWSLETTER = 'FCU - Newsletter',
  CONTRIBUTION = 'FCU - Contribution',
  CONNEXION = 'FCU - Connexion espace gestionnaire',
  GESTIONNAIRES = 'FCU - Gestionnaires',
  GESTIONNAIRES_API = 'FCU - Gestionnaires API',
  NETWORKS = 'FCU - Réseaux de chaleur - 2023',
  COLD_NETWORKS = 'FCU - Réseaux de froid - 2023',
  FUTUR_NETWORKS = 'FCU - Futur réseaux de chaleur',
  MODIFICATIONS_RESEAU = 'FCU - Modifications réseau',
  DEMANDES_ELIGIBILITES = 'FCU - test en masse',
  UTILISATEURS_EMAILS = 'FCU - Utilisateurs emails',
}
