import type { RuleName } from '@betagouv/france-chaleur-urbaine-publicodes';

import type { LocationInfoResponse } from '@/pages/api/location-infos';

export type ModeDeChauffageType = ('individuel' | 'collectif')[];

export const modesDeChauffage = [
  {
    categorie: 'Réseaux de chaleur',
    coutPublicodeKey: 'Réseaux de chaleur',
    emissionsCO2PublicodesKey: 'Réseaux de chaleur x Collectif',
    grandPublicMode: true,
    label: 'Réseau de chaleur',
    reversible: false,
    tertiaire: true,
    type: ['individuel', 'collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'Granulés',
    coutPublicodeKey: 'Chaudière à granulés coll',
    emissionsCO2PublicodesKey: 'Chaudière à granulés coll x Collectif',
    grandPublicMode: false,
    label: 'Chaudière à granulés collective',
    reversible: false,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'Gaz',
    coutPublicodeKey: 'Gaz coll avec cond',
    emissionsCO2PublicodesKey: 'Gaz coll avec cond x Collectif',
    grandPublicMode: true,
    label: 'Gaz à condensation collectif',
    reversible: false,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'Gaz',
    coutPublicodeKey: 'Gaz coll sans cond',
    emissionsCO2PublicodesKey: 'Gaz coll sans cond x Collectif',
    grandPublicMode: true,
    label: 'Gaz sans condensation collectif',
    reversible: false,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'Fioul',
    coutPublicodeKey: 'Fioul coll',
    emissionsCO2PublicodesKey: 'Fioul coll x Collectif',
    grandPublicMode: true,
    label: 'Fioul collectif',
    reversible: false,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC air-air coll',
    emissionsCO2PublicodesKey: 'PAC air-air x Collectif',
    grandPublicMode: false,
    label: 'PAC air/air collective',
    reversible: true,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC air-eau coll',
    emissionsCO2PublicodesKey: 'PAC air-eau x Collectif',
    grandPublicMode: false,
    label: 'PAC air/eau collective',
    reversible: true,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC eau-eau coll',
    emissionsCO2PublicodesKey: 'PAC eau-eau x Collectif',
    grandPublicMode: false,
    label: 'PAC eau/eau collective',
    reversible: false,
    tertiaire: true,
    type: ['collectif'] as ModeDeChauffageType,
  },
  {
    categorie: 'Granulés',
    coutPublicodeKey: 'Poêle à granulés indiv',
    emissionsCO2PublicodesKey: 'Poêle à granulés indiv x Individuel',
    grandPublicMode: false,
    label: 'Poêle à granulés individuel',
    reversible: false,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },
  {
    categorie: 'Gaz',
    coutPublicodeKey: 'Gaz indiv avec cond',
    emissionsCO2PublicodesKey: 'Gaz indiv avec cond x Individuel',
    grandPublicMode: true,
    label: 'Gaz à condensation individuel',
    reversible: false,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },
  {
    categorie: 'Gaz',
    coutPublicodeKey: 'Gaz indiv sans cond',
    emissionsCO2PublicodesKey: 'Gaz indiv sans cond x Individuel',
    grandPublicMode: true,
    label: 'Gaz sans condensation individuel',
    reversible: false,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },

  {
    categorie: 'Fioul',
    coutPublicodeKey: 'Fioul indiv',
    emissionsCO2PublicodesKey: 'Fioul indiv x Individuel',
    grandPublicMode: true,
    label: 'Fioul individuel',
    reversible: false,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },

  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC air-air indiv',
    emissionsCO2PublicodesKey: 'PAC air-air x Individuel',
    grandPublicMode: false,
    label: 'PAC air/air individuelle',
    reversible: true,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },

  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC air-eau indiv',
    emissionsCO2PublicodesKey: 'PAC air-eau x Individuel',
    grandPublicMode: false,
    label: 'PAC air/eau individuelle',
    reversible: true,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },

  {
    categorie: 'PAC',
    coutPublicodeKey: 'PAC eau-eau indiv',
    emissionsCO2PublicodesKey: 'PAC eau-eau x Individuel',
    grandPublicMode: false,
    label: 'PAC eau/eau individuelle',
    reversible: false,
    tertiaire: false,
    type: ['individuel'] as ModeDeChauffageType,
  },
  {
    categorie: 'Radiateur électrique',
    coutPublicodeKey: 'Radiateur électrique',
    emissionsCO2PublicodesKey: 'Radiateur électrique x Individuel',
    grandPublicMode: false,
    label: 'Radiateur électrique individuel',
    reversible: false,
    tertiaire: true,
    type: ['individuel'] as ModeDeChauffageType,
  },
] as const;

export type ModeDeChauffage = (typeof modesDeChauffage)[number]['label'];

export const addresseToPublicodesRules = {
  'caractéristique réseau de chaleur . contenu CO2': (infos) => infos.nearestReseauDeChaleur?.['contenu CO2'],
  'caractéristique réseau de chaleur . contenu CO2 ACV': (infos) => infos.nearestReseauDeChaleur?.['contenu CO2 ACV'],
  'caractéristique réseau de chaleur . livraisons totales': (infos) => infos.nearestReseauDeChaleur?.livraisons_totale_MWh,
  'caractéristique réseau de chaleur . part fixe': (infos) => infos.nearestReseauDeChaleur?.['PF%'],
  'caractéristique réseau de chaleur . part variable': (infos) => infos.nearestReseauDeChaleur?.['PV%'],
  'caractéristique réseau de chaleur . prix moyen': (infos) => infos.nearestReseauDeChaleur?.PM,
  'caractéristique réseau de chaleur . production totale': (infos) => infos.nearestReseauDeChaleur?.production_totale_MWh,
  'caractéristique réseau de chaleur . taux EnRR': (infos) => infos.nearestReseauDeChaleur?.['Taux EnR&R'],

  'caractéristique réseau de froid . contenu CO2': (infos) => infos.nearestReseauDeFroid?.['contenu CO2'],
  'caractéristique réseau de froid . contenu CO2 ACV': (infos) => infos.nearestReseauDeFroid?.['contenu CO2 ACV'],
  'caractéristique réseau de froid . livraisons totales': (infos) => infos.nearestReseauDeFroid?.livraisons_totale_MWh,
  'caractéristique réseau de froid . production totale': (infos) => infos.nearestReseauDeFroid?.production_totale_MWh,

  'code département': (infos) => `'${infos.infosVille.departement_id}'`,
  'température de référence chaud commune': (infos) => +infos.infosVille.temperature_ref_altitude_moyenne,
} as const satisfies Partial<Record<RuleName, (infos: LocationInfoResponse) => any>>;

export const addresseToPublicodesRulesKeys = Object.keys(addresseToPublicodesRules) as RuleName[];
