import type { AirtableLegacyRecord } from '@/modules/demands/types';

export const demand: AirtableLegacyRecord = {
  Adresse: '10 Avenue des Lilas 75019 Paris',
  'Affecté à': 'SOLENA',
  'Code Postal': '75019',
  Conso: 372.15,
  'Date de la demande': '2024-07-31T09:33:00.000Z',
  'Date demandes': '2024-07-31',
  Departement: 'Paris',
  'Distance au réseau': 215,
  'Emails envoyés': 'Nouvel envoi',
  'en PDP': 'Oui',
  Gestionnaires: ['Paris', 'SOLENA_Paris', 'SOLENA', 'SOLENA_IDF', 'SIPPEREC', 'SOLENA_7501A'],
  'Gestionnaires validés': true,
  'ID BNB': '99887766',
  'ID Conso': 123456,
  'Identifiant réseau': '7501A',
  Latitude: 48.885488,
  Logement: 85,
  Longitude: 2.375215,
  Mail: 'a.martin@email.com',
  'Mode de chauffage': 'Fioul',
  Nom: 'MARTIN',
  'Nom réseau': 'Réseau de Paris Nord',
  'Notification envoyé': '2024-08-02',
  'N° de dossier': 5501,
  'Prise de contact': true,
  Prénom: 'ALICE',
  Region: 'Île-de-France',
  Sondage: 'Article sur un site internet',
  Structure: 'Syndicat de copropriété',
  'Type de chauffage': 'Individuel',
  Téléphone: '0612345678',
  Ville: 'Paris',
};
