type Departement = {
  nom: string;
  codeDepartement: string;
  djuMoyenne: number;
  zoneClimatique: string;
};

export const departements: Departement[] = [
  {
    nom: 'AIN',
    codeDepartement: '1',
    djuMoyenne: 2042,
    zoneClimatique: 'H1',
  },
  {
    nom: 'AISNE',
    codeDepartement: '2',
    djuMoyenne: 2156,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ALLIER',
    codeDepartement: '3',
    djuMoyenne: 2018,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ALPES-DE-HAUTE',
    codeDepartement: '4',
    djuMoyenne: 1726,
    zoneClimatique: 'H2',
  },
  {
    nom: 'HAUTES-ALPES',
    codeDepartement: '5',
    djuMoyenne: 2236,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ALPES-MARITIMES',
    codeDepartement: '6',
    djuMoyenne: 939,
    zoneClimatique: 'H3',
  },
  {
    nom: 'ARDECHE',
    codeDepartement: '7',
    djuMoyenne: 1639,
    zoneClimatique: 'H2',
  },
  {
    nom: 'ARDENNES',
    codeDepartement: '8',
    djuMoyenne: 2344,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ARIEGE',
    codeDepartement: '9',
    djuMoyenne: 1750,
    zoneClimatique: 'H2',
  },
  {
    nom: 'AUBE',
    codeDepartement: '10',
    djuMoyenne: 2090,
    zoneClimatique: 'H1',
  },
  {
    nom: 'AUDE',
    codeDepartement: '11',
    djuMoyenne: 1410,
    zoneClimatique: 'H3',
  },
  {
    nom: 'AVEYRON',
    codeDepartement: '12',
    djuMoyenne: 2146,
    zoneClimatique: 'H2',
  },
  {
    nom: 'BOUCHES-DU-RHONE',
    codeDepartement: '13',
    djuMoyenne: 1188,
    zoneClimatique: 'H3',
  },
  {
    nom: 'CALVADOS',
    codeDepartement: '14',
    djuMoyenne: 1928,
    zoneClimatique: 'H1',
  },
  {
    nom: 'CANTAL',
    codeDepartement: '15',
    djuMoyenne: 2269,
    zoneClimatique: 'H1',
  },
  {
    nom: 'CHARENTE',
    codeDepartement: '16',
    djuMoyenne: 1525,
    zoneClimatique: 'H2',
  },
  {
    nom: 'CHARENTE-MARITIME',
    codeDepartement: '17',
    djuMoyenne: 1465,
    zoneClimatique: 'H2',
  },
  {
    nom: 'CHER',
    codeDepartement: '18',
    djuMoyenne: 1897,
    zoneClimatique: 'H2',
  },
  {
    nom: 'CORREZE',
    codeDepartement: '19',
    djuMoyenne: 1676,
    zoneClimatique: 'H1',
  },
  {
    nom: 'CORSE-DU-SUD',
    codeDepartement: '2A',
    djuMoyenne: 979,
    zoneClimatique: 'H3',
  },
  {
    nom: 'HAUTE-CORSE',
    codeDepartement: '2B',
    djuMoyenne: 972,
    zoneClimatique: 'H3',
  },
  {
    nom: "COTE-D'OR",
    codeDepartement: '21',
    djuMoyenne: 2148,
    zoneClimatique: 'H1',
  },
  {
    nom: "COTES-D'ARMOR",
    codeDepartement: '22',
    djuMoyenne: 1819,
    zoneClimatique: 'H2',
  },
  {
    nom: 'CREUSE',
    codeDepartement: '23',
    djuMoyenne: 2170,
    zoneClimatique: 'H1',
  },
  {
    nom: 'DORDOGNE',
    codeDepartement: '24',
    djuMoyenne: 1650,
    zoneClimatique: 'H2',
  },
  {
    nom: 'DOUBS',
    codeDepartement: '25',
    djuMoyenne: 2112,
    zoneClimatique: 'H1',
  },
  {
    nom: 'DROME',
    codeDepartement: '26',
    djuMoyenne: 1542,
    zoneClimatique: 'H2',
  },
  {
    nom: 'EURE',
    codeDepartement: '27',
    djuMoyenne: 2057,
    zoneClimatique: 'H1',
  },
  {
    nom: 'EURE-ET-LOIR',
    codeDepartement: '28',
    djuMoyenne: 2013,
    zoneClimatique: 'H1',
  },
  {
    nom: 'FINISTERE',
    codeDepartement: '29',
    djuMoyenne: 1729,
    zoneClimatique: 'H2',
  },
  {
    nom: 'GARD',
    codeDepartement: '30',
    djuMoyenne: 1236,
    zoneClimatique: 'H3',
  },
  {
    nom: 'HAUTE-GARONNE',
    codeDepartement: '31',
    djuMoyenne: 1459,
    zoneClimatique: 'H2',
  },
  {
    nom: 'GERS',
    codeDepartement: '32',
    djuMoyenne: 1578,
    zoneClimatique: 'H2',
  },
  {
    nom: 'GIRONDE',
    codeDepartement: '33',
    djuMoyenne: 1388,
    zoneClimatique: 'H2',
  },
  {
    nom: 'HERAULT',
    codeDepartement: '34',
    djuMoyenne: 1206,
    zoneClimatique: 'H3',
  },
  {
    nom: 'ILLE-ET-VILAINE',
    codeDepartement: '35',
    djuMoyenne: 1753,
    zoneClimatique: 'H2',
  },
  {
    nom: 'INDRE',
    codeDepartement: '36',
    djuMoyenne: 1932,
    zoneClimatique: 'H2',
  },
  {
    nom: 'INDRE-ET-LOIRE',
    codeDepartement: '37',
    djuMoyenne: 1812,
    zoneClimatique: 'H2',
  },
  {
    nom: 'ISERE',
    codeDepartement: '38',
    djuMoyenne: 2189,
    zoneClimatique: 'H1',
  },
  {
    nom: 'JURA',
    codeDepartement: '39',
    djuMoyenne: 2021,
    zoneClimatique: 'H1',
  },
  {
    nom: 'LANDES',
    codeDepartement: '40',
    djuMoyenne: 1480,
    zoneClimatique: 'H2',
  },
  {
    nom: 'LOIR-ET-CHER',
    codeDepartement: '41',
    djuMoyenne: 1985,
    zoneClimatique: 'H2',
  },
  {
    nom: 'LOIRE',
    codeDepartement: '42',
    djuMoyenne: 2062,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUTE-LOIRE',
    codeDepartement: '43',
    djuMoyenne: 2600,
    zoneClimatique: 'H1',
  },
  {
    nom: 'LOIRE-ATLANTIQUE',
    codeDepartement: '44',
    djuMoyenne: 1650,
    zoneClimatique: 'H2',
  },
  {
    nom: 'LOIRET',
    codeDepartement: '45',
    djuMoyenne: 1990,
    zoneClimatique: 'H1',
  },
  {
    nom: 'LOT',
    codeDepartement: '46',
    djuMoyenne: 1713,
    zoneClimatique: 'H2',
  },
  {
    nom: 'LOT-ET-GARONNE',
    codeDepartement: '47',
    djuMoyenne: 1536,
    zoneClimatique: 'H2',
  },
  {
    nom: 'LOZERE',
    codeDepartement: '48',
    djuMoyenne: 2496,
    zoneClimatique: 'H2',
  },
  {
    nom: 'MAINE-ET-LOIRE',
    codeDepartement: '49',
    djuMoyenne: 1711,
    zoneClimatique: 'H2',
  },
  {
    nom: 'MANCHE',
    codeDepartement: '50',
    djuMoyenne: 1824,
    zoneClimatique: 'H2',
  },
  {
    nom: 'MARNE',
    codeDepartement: '51',
    djuMoyenne: 2144,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUTE-MARNE',
    codeDepartement: '52',
    djuMoyenne: 2387,
    zoneClimatique: 'H1',
  },
  {
    nom: 'MAYENNE',
    codeDepartement: '53',
    djuMoyenne: 1900,
    zoneClimatique: 'H2',
  },
  {
    nom: 'MEURTHE-ET-MOSELLE',
    codeDepartement: '54',
    djuMoyenne: 2214,
    zoneClimatique: 'H1',
  },
  {
    nom: 'MEUSE',
    codeDepartement: '55',
    djuMoyenne: 2272,
    zoneClimatique: 'H1',
  },
  {
    nom: 'MORBIHAN',
    codeDepartement: '56',
    djuMoyenne: 1690,
    zoneClimatique: 'H2',
  },
  {
    nom: 'MOSELLE',
    codeDepartement: '57',
    djuMoyenne: 2219,
    zoneClimatique: 'H1',
  },
  {
    nom: 'NIEVRE',
    codeDepartement: '58',
    djuMoyenne: 2050,
    zoneClimatique: 'H1',
  },
  {
    nom: 'NORD',
    codeDepartement: '59',
    djuMoyenne: 2042,
    zoneClimatique: 'H1',
  },
  {
    nom: 'OISE',
    codeDepartement: '60',
    djuMoyenne: 2146,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ORNE',
    codeDepartement: '61',
    djuMoyenne: 2015,
    zoneClimatique: 'H1',
  },
  {
    nom: 'PAS-DE-CALAIS',
    codeDepartement: '62',
    djuMoyenne: 1965,
    zoneClimatique: 'H1',
  },
  {
    nom: 'PUY-DE-DOME',
    codeDepartement: '63',
    djuMoyenne: 1897,
    zoneClimatique: 'H1',
  },
  {
    nom: 'PYRENEES-ATLANTIQUES',
    codeDepartement: '64',
    djuMoyenne: 1458,
    zoneClimatique: 'H2',
  },
  {
    nom: 'HAUTES-PYRENEES',
    codeDepartement: '65',
    djuMoyenne: 1693,
    zoneClimatique: 'H2',
  },
  {
    nom: 'PYRENEES-ORIENTALES',
    codeDepartement: '66',
    djuMoyenne: 1047,
    zoneClimatique: 'H3',
  },
  {
    nom: 'BAS-RHIN',
    codeDepartement: '67',
    djuMoyenne: 2117,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUT-RHIN',
    codeDepartement: '68',
    djuMoyenne: 2203,
    zoneClimatique: 'H1',
  },
  {
    nom: 'RHONE',
    codeDepartement: '69',
    djuMoyenne: 1796,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUTE-SAONE',
    codeDepartement: '70',
    djuMoyenne: 2277,
    zoneClimatique: 'H1',
  },
  {
    nom: 'SAONE-ET-LOIRE',
    codeDepartement: '71',
    djuMoyenne: 1935,
    zoneClimatique: 'H1',
  },
  {
    nom: 'SARTHE',
    codeDepartement: '72',
    djuMoyenne: 1772,
    zoneClimatique: 'H2',
  },
  {
    nom: 'SAVOIE',
    codeDepartement: '73',
    djuMoyenne: 2357,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUTE-SAVOIE',
    codeDepartement: '74',
    djuMoyenne: 2245,
    zoneClimatique: 'H1',
  },
  {
    nom: 'PARIS',
    codeDepartement: '75',
    djuMoyenne: 1718,
    zoneClimatique: 'H1',
  },
  {
    nom: 'SEINE-MARITIME',
    codeDepartement: '76',
    djuMoyenne: 2079,
    zoneClimatique: 'H1',
  },
  {
    nom: 'SEINE-ET-MARNE',
    codeDepartement: '77',
    djuMoyenne: 1982,
    zoneClimatique: 'H1',
  },
  {
    nom: 'YVELINES',
    codeDepartement: '78',
    djuMoyenne: 2017,
    zoneClimatique: 'H1',
  },
  {
    nom: 'DEUX-SEVRES',
    codeDepartement: '79',
    djuMoyenne: 1688,
    zoneClimatique: 'H2',
  },
  {
    nom: 'SOMME',
    codeDepartement: '80',
    djuMoyenne: 2019,
    zoneClimatique: 'H1',
  },
  {
    nom: 'TARN',
    codeDepartement: '81',
    djuMoyenne: 1622,
    zoneClimatique: 'H2',
  },
  {
    nom: 'TARN-ET-GARONNE',
    codeDepartement: '82',
    djuMoyenne: 1559,
    zoneClimatique: 'H3',
  },
  {
    nom: 'VAR',
    codeDepartement: '83',
    djuMoyenne: 1224,
    zoneClimatique: 'H3',
  },
  {
    nom: 'VAUCLUSE',
    codeDepartement: '84',
    djuMoyenne: 1464,
    zoneClimatique: 'H2',
  },
  {
    nom: 'VENDEE',
    codeDepartement: '85',
    djuMoyenne: 1730,
    zoneClimatique: 'H2',
  },
  {
    nom: 'VIENNE',
    codeDepartement: '86',
    djuMoyenne: 1823,
    zoneClimatique: 'H2',
  },
  {
    nom: 'HAUTE-VIENNE',
    codeDepartement: '87',
    djuMoyenne: 1943,
    zoneClimatique: 'H1',
  },
  {
    nom: 'VOSGES',
    codeDepartement: '88',
    djuMoyenne: 2346,
    zoneClimatique: 'H1',
  },
  {
    nom: 'YONNE',
    codeDepartement: '89',
    djuMoyenne: 2085,
    zoneClimatique: 'H1',
  },
  {
    nom: 'TERRITOIRE DE BELFORT',
    codeDepartement: '90',
    djuMoyenne: 2255,
    zoneClimatique: 'H1',
  },
  {
    nom: 'ESSONNE',
    codeDepartement: '91',
    djuMoyenne: 1893,
    zoneClimatique: 'H1',
  },
  {
    nom: 'HAUTS-DE-SEINE',
    codeDepartement: '92',
    djuMoyenne: 1764,
    zoneClimatique: 'H1',
  },
  {
    nom: 'SEINE-SAINT-DENIS',
    codeDepartement: '93',
    djuMoyenne: 1873,
    zoneClimatique: 'H1',
  },
  {
    nom: 'VAL-DE-MARNE',
    codeDepartement: '94',
    djuMoyenne: 1764,
    zoneClimatique: 'H1',
  },
  {
    nom: "VAL-D'OISE",
    codeDepartement: '95',
    djuMoyenne: 1899,
    zoneClimatique: 'H1',
  },
];
