/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, JSONColumnType } from 'kysely';

import type { AirtableLegacyRecord } from '@/modules/demands/types';
import type { EventType } from '@/modules/events/constants';
import type { UserRole } from '@/types/enum/UserRole';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiAccounts {
  gestionnaires: string[] | null;
  key: string;
  name: string | null;
  networks: string[] | null;
  token: string;
}

export interface BatimentsRaccordesReseauxChaleurFroidTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface BdnbBatiments {
  adresse_cle_interop_adr_principale_ban: string | null;
  adresse_libelle_adr_principale_ban: string | null;
  constructions: { construction_id: string; rnb_id: string }[] | null;
  batiment_groupe_id: string;
  code_commune_insee: string | null;
  dle_elec_multimillesime_conso_pro: Numeric | null;
  dle_elec_multimillesime_conso_res: Numeric | null;
  dle_elec_multimillesime_conso_tot: Numeric | null;
  dle_gaz_multimillesime_conso_pro: Numeric | null;
  dle_gaz_multimillesime_conso_res: Numeric | null;
  dle_gaz_multimillesime_conso_tot: Numeric | null;
  dle_reseaux_multimillesime_conso_pro: Numeric | null;
  dle_reseaux_multimillesime_conso_res: Numeric | null;
  dle_reseaux_multimillesime_conso_tot: Numeric | null;
  dpe_representatif_logement_classe_bilan_dpe: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
  dpe_representatif_logement_classe_emission_ges: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | null;
  dpe_representatif_logement_surface_habitable_immeuble: number | null;
  dpe_representatif_logement_type_batiment_dpe: 'appartement' | 'immeuble' | 'maison' | null;
  dpe_representatif_logement_type_dpe:
    | 'dpe arrêté 2012 3cl immeuble'
    | 'dpe arrêté 2012 3cl logement'
    | 'dpe arrêté 2012 facture immeuble'
    | 'dpe arrêté 2012 facture logement'
    | 'dpe arrêté 2021 3cl immeuble'
    | 'dpe arrêté 2021 3cl logement'
    | 'dpe arrêté 2021 re2020 immeuble'
    | 'dpe arrêté 2021 re2020 logement'
    | 'dpe arrêté 2021 rt2012 immeuble'
    | 'dpe arrêté 2021 rt2012 logement'
    | null;
  dpe_representatif_logement_type_energie_chauffage:
    | 'bois'
    | 'charbon'
    | 'electricite'
    | 'fioul'
    | 'gaz'
    | 'gpl/butane/propane'
    | 'reseau de chaleur'
    | 'solaire'
    | null;
  dpe_representatif_logement_type_generateur_chauffage: string | null; // chaudiere*, chauffage*, generateur*, pac*, poele*, radiateurs*, reseau*
  dpe_representatif_logement_type_installation_chauffage: 'collectif' | 'individuel' | null;
  ffo_bat_annee_construction: number | null;
  ffo_bat_nb_log: number | null;
  ffo_bat_usage_niveau_1_txt:
    | 'Dépendance'
    | 'Résidentiel collectif'
    | 'Résidentiel individuel'
    | 'Secondaire'
    | 'Tertiaire & Autres'
    | null;
  geom: string | null;
  id: number | null;
  rnc_l_nom_copro: string[] | null;
  synthese_propriete_usage:
    | 'Dépendance'
    | 'Indifférencié'
    | 'Résidentiel collectif'
    | 'Résidentiel individuel'
    | 'Secondaire'
    | 'Tertiaire'
    | null;
}

export interface BdnbBatimentsTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface BesoinsEnChaleurBatiments {
  chauf_mwh: Numeric | null;
  com_insee: string | null;
  ecs_mwh: Numeric | null;
  en_chauf: string | null;
  en_ecs: string | null;
  froid_mwh: Numeric | null;
  geom: string | null;
  idbatiment: string | null;
  inst_chauf: string | null;
  inst_ecs: string | null;
  ogc_fid: Generated<number>;
  part_ter: Numeric | null;
  sdp_m2: Numeric | null;
  secteur: string | null;
}

export interface BesoinsEnChaleurIndustrieCommunesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface BesoinsEnChaleurTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface Communes {
  altitude_moyenne: number;
  code_postal: string;
  commune: string;
  departement_id: string;
  id: string;
  source: string;
  temperature_ref_altitude_moyenne: Numeric;
}

export interface CommunesFortPotentielPourCreationReseauxChaleurTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface Demands {
  airtable_id: string | null;
  comment_gestionnaire: string | null;
  comment_fcu: string | null;
  created_at: Generated<Timestamp>;
  deleted_at?: Timestamp | null;
  id: Generated<string>;
  legacy_values: JSONColumnType<AirtableLegacyRecord>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface DemandEmails {
  airtable_id: string | null;
  body: string;
  cc: string | null;
  created_at: Generated<Timestamp>;
  deleted_at?: Timestamp | null;
  demand_id: string;
  email_key: string;
  id: Generated<string>;
  object: string;
  reply_to: string | null;
  sent_at: Timestamp | string | null;
  signature: string | null;
  to: string;
  updated_at: Generated<Timestamp>;
  user_email: string;
}

export interface Departements {
  annee: string;
  dju_chaud_moyen: Numeric | null;
  dju_froid_moyen: Numeric | null;
  id: string;
  nom_departement: string;
  source: string | null;
  sous_zone_climatique: string | null;
  zone_climatique: string | null;
}

export interface DonneesDeConsos {
  adresse: string;
  code_grand: 'R' | 'T' | 'I' | 'A' | 'X';
  conso_nb: number;
  geom: string;
  pdl_nb: number;
}

export interface DonneesDeConsosTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface EligibilityDemands {
  created_at: Generated<Timestamp | null>;
  eligibility_test_id: string;
  email: string;
  id: Generated<string>;
}

export interface EligibilityDemandsAddresses {
  ban_address: string | null;
  ban_score: number | null;
  ban_valid: boolean | null;
  eligibility_status: Json | null;
  geom: string | null;
  id: Generated<string>;
  source_address: string;
  test_id: string;
}

export interface EligibilityTests {
  addresses_count: number | null;
  created_at: Generated<Timestamp | null>;
  eligibile_count: number | null;
  error_count: number | null;
  file: Generated<string>;
  hash: string;
  id: Generated<string>;
  in_error: boolean | null;
  result: string | null;
  status: Generated<string>;
  version: number;
}

export interface EmailTemplates {
  body: string;
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  subject: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface EnrrMobilisablesFrichesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface EnrrMobilisablesParkingsTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface EnrrMobilisablesThalassothermieTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface EnrrMobilisablesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface EtudesEnCours {
  commune_ids: string[];
  communes: string | null;
  geom: string;
  id: number;
  launched_at: Timestamp;
  maitre_ouvrage: string;
  status: string;
}

export interface EnrrMobilisablesZonesGeothermieProfondeTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface Epci {
  code: string;
  membres: JSONColumnType<
    {
      code: string;
      nom: string;
    }[]
  >;
  nom: string;
  type: string;
}

export interface Ept {
  code: string;
  membres: JSONColumnType<
    {
      code: string;
      nom: string;
    }[]
  >;
  nom: string;
  type: string;
}

export interface EtudesEnCoursTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface Events {
  author_id: string | null;
  context_id: string | null;
  context_type: string | null;
  created_at: Generated<Timestamp>;
  data: Generated<Json>;
  id: Generated<string>;
  type: EventType;
}

export interface IgnCommunes {
  geom: string | null;
  geom_150m: string | null;
  id: string | null;
  insee_arr: string | null;
  insee_can: string | null;
  insee_com: string | null;
  insee_dep: string | null;
  insee_reg: string | null;
  nom: string | null;
  nom_m: string | null;
  ogc_fid: Generated<number>;
  population: Numeric | null;
  siren_epci: string | null;
  statut: string | null;
}

export interface IgnDepartements {
  geom: string | null;
  id: string | null;
  insee_dep: string | null;
  insee_reg: string | null;
  nom: string | null;
  nom_m: string | null;
  ogc_fid: Generated<number>;
}

export interface IgnRegions {
  geom: string | null;
  id: string | null;
  insee_reg: string | null;
  nom: string | null;
  nom_m: string | null;
  ogc_fid: Generated<number>;
}

export interface InstallationsGeothermieProfondeTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface InstallationsGeothermieSurfaceEchangeursFermesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface InstallationsGeothermieSurfaceEchangeursOuvertsTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface Jobs {
  created_at: Generated<Timestamp>;
  data: Json;
  entity_id: string | null;
  id: Generated<string>;
  status: 'pending' | 'processing' | 'finished' | 'error';
  result: Json | null;
  type:
    | 'pro_eligibility_test'
    | 'build_tiles'
    | 'sync_geometries_to_airtable'
    | 'sync_metadata_from_airtable'
    | 'pro_eligibility_test_notify_changes';
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface MatomoStats {
  date: Timestamp;
  method: string;
  method_params: string | null;
  period: string;
  stat_key: string | null;
  stat_label: string | null;
  value: number;
}

export interface OuvragesGeothermieSurfaceEchangeursFermesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface OuvragesGeothermieSurfaceEchangeursOuvertsTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface PerimetresGeothermieProfondeTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ProComparateurConfigurations {
  address: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  situation: { address?: string } & Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ProEligibilityTests {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  has_unseen_changes: Generated<boolean>;
  has_unseen_results: boolean;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ProEligibilityTestsAddresses {
  ban_address: string | null;
  ban_score: number | null;
  ban_valid: boolean;
  geom: GeoJSON.Point | null;
  change_viewed_at: Timestamp | null;
  demand_id: string | null;
  /**
   * JSON array storing full history of eligibility status changes. Format: [{"calculated_at": "ISO8601", "eligibility": {...getDetailedEligibilityStatus result...}}]
   */
  eligibility_history: Generated<Json>;
  id: Generated<string>;
  source_address: string;
  test_id: string | null;
}

export interface ProEligibilityTestsAddressesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface QuartiersPrioritairesPolitiqueVille {
  code_qp: string;
  geom: string | null;
  insee_com: string;
  insee_dep: string;
  insee_reg: string;
  lib_com: string;
  lib_dep: string;
  lib_qp: string;
  lib_reg: string;
  fid: Generated<number>;
  siren_epci: string | null;
  source_fid: number | null;
}

export interface QuartiersPrioritairesPolitiqueVille2015AnruTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface QuartiersPrioritairesPolitiqueVille2024Tiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface RaccordementsTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ReseauxDeChaleur {
  adresse_mo: string | null;
  annee_creation: number | null;
  communes: string[] | null;
  communes_insee: string[] | null;
  'contenu CO2': number | null;
  'contenu CO2 ACV': number | null;
  contenu_CO2_2023_tmp: number | null;
  contenu_CO2_ACV_2023_tmp: number | null;
  CP_MO: string | null;
  date_actualisation_pdp: Timestamp | null;
  date_actualisation_trace: Timestamp | null;
  departement: string | null;
  'Dev_reseau%': number | null;
  eau_chaude: string | null;
  eau_surchauffee: string | null;
  fichiers: Json | null;
  geom: string | null;
  geom_update: string | null;
  Gestionnaire: string | null;
  has_PDP: Generated<boolean>;
  has_trace: Generated<boolean>;
  id_fcu: number;
  'Identifiant reseau': string | null;
  informationsComplementaires: string | null;
  livraisons_agriculture_MWh: number | null;
  livraisons_autre_MWh: number | null;
  livraisons_industrie_MWh: number | null;
  livraisons_residentiel_MWh: number | null;
  livraisons_tertiaire_MWh: number | null;
  livraisons_totale_MWh: number | null;
  longueur_reseau: number | null;
  MO: string | null;
  'Moyenne-annee-DPE': string | null;
  nb_pdl: number | null;
  nom_reseau: string | null;
  'PF%': number | null;
  PM: number | null;
  PM_L: number | null;
  PM_T: number | null;
  prod_MWh_autre_chaleur_recuperee: number | null;
  prod_MWh_autres: number | null;
  prod_MWh_autres_ENR: number | null;
  prod_MWh_biogaz: number | null;
  prod_MWh_biomasse_solide: number | null;
  prod_MWh_chaleur_industiel: number | null;
  prod_MWh_charbon: number | null;
  prod_MWh_chaudieres_electriques: number | null;
  prod_MWh_dechets_internes: number | null;
  prod_MWh_fioul_domestique: number | null;
  prod_MWh_fioul_lourd: number | null;
  prod_MWh_gaz_naturel: number | null;
  prod_MWh_geothermie: number | null;
  prod_MWh_GPL: number | null;
  prod_MWh_PAC: number | null;
  prod_MWh_solaire_thermique: number | null;
  prod_MWh_UIOM: number | null;
  production_totale_MWh: number | null;
  puissance_MW_autre_chaleur_recuperee: number | null;
  puissance_MW_autres: number | null;
  puissance_MW_autres_ENR: number | null;
  puissance_MW_biogaz: number | null;
  puissance_MW_biomasse_solide: number | null;
  puissance_MW_chaleur_industiel: number | null;
  puissance_MW_charbon: number | null;
  puissance_MW_chaudieres_electriques: number | null;
  puissance_MW_dechets_internes: number | null;
  puissance_MW_fioul_domestique: number | null;
  puissance_MW_fioul_lourd: number | null;
  puissance_MW_gaz_naturel: number | null;
  puissance_MW_geothermie: number | null;
  puissance_MW_GPL: number | null;
  puissance_MW_PAC: number | null;
  puissance_MW_solaire_thermique: number | null;
  puissance_MW_UIOM: number | null;
  puissance_totale_MW: number | null;
  'PV%': number | null;
  region: string | null;
  'Rend%': number | null;
  'reseaux classes': boolean | null;
  reseaux_techniques: boolean | null;
  tags: string[];
  'Taux EnR&R': number | null;
  vapeur: string | null;
  ville_mo: string | null;
  website_gestionnaire: string | null;
}

export interface ReseauxDeChaleurTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ReseauxDeFroid {
  adresse_mo: string | null;
  annee_creation: number | null;
  communes: string[] | null;
  communes_insee: string[] | null;
  'contenu CO2': number | null;
  'contenu CO2 ACV': number | null;
  contenu_CO2_2023_tmp: number | null;
  contenu_CO2_ACV_2023_tmp: number | null;
  CP_MO: string | null;
  date_actualisation_trace: Timestamp | null;
  departement: string | null;
  fichiers: Json | null;
  geom: string | null;
  geom_update: string | null;
  Gestionnaire: string | null;
  has_trace: Generated<boolean>;
  id_fcu: number;
  'Identifiant reseau': string | null;
  informationsComplementaires: string | null;
  livraisons_agriculture_MWh: number | null;
  livraisons_autre_MWh: number | null;
  livraisons_industrie_MWh: number | null;
  livraisons_residentiel_MWh: number | null;
  livraisons_tertiaire_MWh: number | null;
  livraisons_totale_MWh: number | null;
  longueur_reseau: number | null;
  MO: string | null;
  'Moyenne-annee-DPE': string | null;
  nb_pdl: number | null;
  nom_reseau: string | null;
  production_totale_MWh: number | null;
  puissance_totale_MW: number | null;
  region: string | null;
  'Rend%': number | null;
  'reseaux classes': boolean | null;
  'Taux EnR&R': number | null;
  ville_mo: string | null;
  website_gestionnaire: string | null;
}

export interface ReseauxDeFroidTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface RessourcesGeothermalesNappesTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface AssignmentRules {
  id: string;
  search_pattern: string;
  result: string;
  active: boolean;
  created_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface TagsReminders {
  author_id: string | null;
  created_at: Generated<Timestamp>;
  tag_id: string;
}

export interface Users {
  accepted_cgu_at: Date | null;
  activated_at: Date | null;
  activation_token: string | null;
  active: Generated<boolean>;
  created_at: Generated<Date | null>;
  email: string;
  first_name: string | null;
  from_api: string | null;
  gestionnaires: string[] | null;
  gestionnaires_from_api: string[] | null;
  id: Generated<string>;
  last_connection: Date | null;
  last_name: string | null;
  optin_at: Date | null;
  password: string;
  phone: string | null;
  receive_new_demands: boolean | null;
  receive_old_demands: boolean | null;
  reset_token: string | null;
  role: UserRole;
  signature: string | null;
  status: 'pending_email_confirmation' | 'valid';
  structure_name: string | null;
  structure_other: string | null;
  structure_type: string | null;
}

export interface ZoneAPotentielChaud {
  bat_imp: Numeric | null;
  chauf_mwh: Numeric | null;
  code_com_i: string | null;
  com_arr: string | null;
  dep: string | null;
  ecs_mwh: Numeric | null;
  geom: string | null;
  geothermie: Numeric | null;
  id_zone: string | null;
  ogc_fid: Generated<number>;
  part_ecs: Numeric | null;
  part_ter: Numeric | null;
  rdt_bt: Numeric | null;
  rdt_ht: Numeric | null;
  sol_moy: Numeric | null;
  surf_cap_1: Numeric | null;
  surf_capt_: Numeric | null;
  surf_sol_1: Numeric | null;
  surf_sol_8: Numeric | null;
}

export interface ZoneAPotentielFroid {
  bat_imp: Numeric | null;
  bes_min: string | null;
  com_insee: string | null;
  dens_min: string | null;
  dep: string | null;
  dist_con: string | null;
  filere: string | null;
  froid_mwh: Numeric | null;
  geom: string | null;
  icu_sensib: Numeric | null;
  icu_val: string | null;
  id_zone: string | null;
  ogc_fid: Generated<number>;
  part_ter: Numeric | null;
  reg: string | null;
  type_zone: string | null;
}

export interface ZoneAPotentielChaudTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZoneAPotentielFroidTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZoneAPotentielFortChaud {
  bat_imp: Numeric | null;
  chauf_mwh: Numeric | null;
  code_com_i: string | null;
  com_arr: string | null;
  dep: string | null;
  ecs_mwh: Numeric | null;
  geom: string | null;
  geothermie: Numeric | null;
  id_zone: string | null;
  ogc_fid: Generated<number>;
  part_ecs: Numeric | null;
  part_ter: Numeric | null;
  rdt_bt: Numeric | null;
  rdt_ht: Numeric | null;
  sol_moy: Numeric | null;
  surf_cap_1: Numeric | null;
  surf_capt_: Numeric | null;
  surf_sol_1: Numeric | null;
  surf_sol_8: Numeric | null;
}

export interface ZoneAPotentielFortChaudTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZoneAPotentielFortFroid {
  bat_imp: Numeric | null;
  bes_min: string | null;
  com_insee: string | null;
  dens_min: string | null;
  dep: string | null;
  dist_con: string | null;
  filere: string | null;
  froid_mwh: Numeric | null;
  geom: string | null;
  icu_sensib: Numeric | null;
  icu_val: string | null;
  id_zone: string | null;
  ogc_fid: Generated<number>;
  part_ter: Numeric | null;
  reg: string | null;
  type_zone: string | null;
}

export interface ZoneAPotentielFortFroidTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZoneAUrbaniserTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZoneDeDeveloppementPrioritaire {
  id_fcu: number;
  communes: string[] | null;
  communes_insee: string[] | null;
  date_actualisation_trace: Timestamp | null;
  departement: string | null;
  geom: string | null;
  geom_update: string | null;
  'Identifiant reseau': string | null;
  region: string | null;
  reseau_de_chaleur_ids: number[];
  reseau_en_construction_ids: number[];
}

export interface ZoneDeDeveloppementPrioritaireTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface ZonesEtReseauxEnConstruction {
  communes: string[] | null;
  communes_insee: string[] | null;
  date_actualisation_trace: Timestamp | null;
  departement: string | null;
  geom: string | null;
  geom_update: string | null;
  gestionnaire: string | null;
  id_fcu: number;
  is_zone: Generated<boolean>;
  mise_en_service: string | null;
  nom_reseau: string | null;
  region: string | null;
  tags: string[];
}

export interface ZonesEtReseauxEnConstructionTiles {
  tile: Buffer;
  x: Int8;
  y: Int8;
  z: Int8;
}

export interface DB {
  api_accounts: ApiAccounts;
  assignment_rules: AssignmentRules;
  batiments_raccordes_reseaux_chaleur_froid_tiles: BatimentsRaccordesReseauxChaleurFroidTiles;
  bdnb_batiments: BdnbBatiments;
  bdnb_batiments_tiles: BdnbBatimentsTiles;
  besoins_en_chaleur_batiments: BesoinsEnChaleurBatiments;
  besoins_en_chaleur_industrie_communes_tiles: BesoinsEnChaleurIndustrieCommunesTiles;
  besoins_en_chaleur_tiles: BesoinsEnChaleurTiles;
  communes: Communes;
  communes_fort_potentiel_pour_creation_reseaux_chaleur_tiles: CommunesFortPotentielPourCreationReseauxChaleurTiles;
  demands: Demands;
  demand_emails: DemandEmails;
  departements: Departements;
  donnees_de_consos: DonneesDeConsos;
  donnees_de_consos_tiles: DonneesDeConsosTiles;
  eligibility_demands: EligibilityDemands;
  eligibility_demands_addresses: EligibilityDemandsAddresses;
  eligibility_tests: EligibilityTests;
  email_templates: EmailTemplates;
  enrr_mobilisables_friches_tiles: EnrrMobilisablesFrichesTiles;
  enrr_mobilisables_parkings_tiles: EnrrMobilisablesParkingsTiles;
  enrr_mobilisables_thalassothermie_tiles: EnrrMobilisablesThalassothermieTiles;
  enrr_mobilisables_tiles: EnrrMobilisablesTiles;
  enrr_mobilisables_zones_geothermie_profonde_tiles: EnrrMobilisablesZonesGeothermieProfondeTiles;
  epci: Epci;
  ept: Ept;
  etudes_en_cours: EtudesEnCours;
  etudes_en_cours_tiles: EtudesEnCoursTiles;
  events: Events;
  ign_communes: IgnCommunes;
  ign_departements: IgnDepartements;
  ign_regions: IgnRegions;
  installations_geothermie_profonde_tiles: InstallationsGeothermieProfondeTiles;
  installations_geothermie_surface_echangeurs_fermes_tiles: InstallationsGeothermieSurfaceEchangeursFermesTiles;
  installations_geothermie_surface_echangeurs_ouverts_tiles: InstallationsGeothermieSurfaceEchangeursOuvertsTiles;
  jobs: Jobs;
  matomo_stats: MatomoStats;
  ouvrages_geothermie_surface_echangeurs_fermes_tiles: OuvragesGeothermieSurfaceEchangeursFermesTiles;
  ouvrages_geothermie_surface_echangeurs_ouverts_tiles: OuvragesGeothermieSurfaceEchangeursOuvertsTiles;
  perimetres_geothermie_profonde_tiles: PerimetresGeothermieProfondeTiles;
  pro_comparateur_configurations: ProComparateurConfigurations;
  pro_eligibility_tests: ProEligibilityTests;
  pro_eligibility_tests_addresses: ProEligibilityTestsAddresses;
  pro_eligibility_tests_addresses_tiles: ProEligibilityTestsAddressesTiles;
  quartiers_prioritaires_politique_ville_2015_anru_tiles: QuartiersPrioritairesPolitiqueVille2015AnruTiles;
  quartiers_prioritaires_politique_ville_2024_tiles: QuartiersPrioritairesPolitiqueVille2024Tiles;
  quartiers_prioritaires_politique_ville: QuartiersPrioritairesPolitiqueVille;
  raccordements_tiles: RaccordementsTiles;
  reseaux_de_chaleur: ReseauxDeChaleur;
  reseaux_de_chaleur_tiles: ReseauxDeChaleurTiles;
  reseaux_de_froid: ReseauxDeFroid;
  reseaux_de_froid_tiles: ReseauxDeFroidTiles;
  ressources_geothermales_nappes_tiles: RessourcesGeothermalesNappesTiles;
  tags: Tags;
  tags_reminders: TagsReminders;
  users: Users;
  zone_a_potentiel_chaud: ZoneAPotentielChaud;
  zone_a_potentiel_chaud_tiles: ZoneAPotentielChaudTiles;
  zone_a_potentiel_froid: ZoneAPotentielFroid;
  zone_a_potentiel_froid_tiles: ZoneAPotentielFroidTiles;
  zone_a_potentiel_fort_chaud: ZoneAPotentielFortChaud;
  zone_a_potentiel_fort_chaud_tiles: ZoneAPotentielFortChaudTiles;
  zone_a_potentiel_fort_froid: ZoneAPotentielFortFroid;
  zone_a_potentiel_fort_froid_tiles: ZoneAPotentielFortFroidTiles;
  zone_a_urbaniser_tiles: ZoneAUrbaniserTiles;
  zone_de_developpement_prioritaire: ZoneDeDeveloppementPrioritaire;
  zone_de_developpement_prioritaire_tiles: ZoneDeDeveloppementPrioritaireTiles;
  zones_et_reseaux_en_construction: ZonesEtReseauxEnConstruction;
  zones_et_reseaux_en_construction_tiles: ZonesEtReseauxEnConstructionTiles;
}

export type DBTableName = keyof DB;
