import { type DB } from '@/server/db/kysely';

export const allDatabaseTables = [
  'api_accounts',
  'batiments_raccordes_rdc',
  'batiments_raccordes_reseaux_chaleur_froid_tiles',
  'bdnb_registre2022_aura',
  'bdnb_registre2022_bourgogne-franche-comte',
  'bdnb_registre2022_bretagne',
  'bdnb_registre2022_centre-val_de_loire',
  'bdnb_registre2022_corse',
  'bdnb_registre2022_grand_est',
  'bdnb_registre2022_hauts-de-france',
  'bdnb_registre2022_ile-de-france',
  'bdnb_registre2022_normandie',
  'bdnb_registre2022_nouvelle-aquitaine',
  'bdnb_registre2022_occitanie',
  'bdnb_registre2022_paca',
  'bdnb_registre2022_pays-de-la-loire',
  'besoins_en_chaleur_industrie_communes_tiles',
  'besoins_en_chaleur_tiles',
  'bnb - adresse_tiles',
  'bnb - batiment_tiles',
  'bnb_auvergne-rhone-alpes-batiment_adresse',
  'bnb_bourgogne-franche-comte-batiment_adresse',
  'bnb_bretagne-batiment_adresse',
  'bnb_centre-val-de-loire-batiment_adresse',
  'bnb_corse-batiment_adresse',
  'bnb_grand-est-batiment_adresse',
  'bnb_hauts-de-france-batiment_adresse',
  'bnb_idf - batiment_adresse',
  'bnb_normandie-batiment_adresse',
  'bnb_nouvelle-aquitaine-batiment_adresse',
  'bnb_occitanie-batiment_adresse',
  'bnb_pays-de-la-loire-batiment_adresse',
  'bnb_provence-alpes-cote-d_azur-batiment_adresse',
  'communes',
  'communes_fort_potentiel_pour_creation_reseaux_chaleur_tiles',
  'departements',
  'donnees_de_consos',
  'donnees_de_consos_tiles',
  'eligibility_demands',
  'eligibility_tests',
  'users',
  'email_templates',
  'enrr_mobilisables_friches_tiles',
  'enrr_mobilisables_parkings_tiles',
  'enrr_mobilisables_tiles',
  'etudes_en_cours',
  'etudes_en_cours_tiles',
  'ign_communes',
  'ign_departements',
  'ign_regions',
  'jobs',
  'matomo_stats',
  'network_iris',
  'pro_comparateur_configurations',
  'pro_eligibility_tests',
  'pro_eligibility_tests_addresses',
  'raccordements_tiles',
  'regions',
  'registre_copro_r11_220125',
  'reseaux_de_chaleur',
  'reseaux_de_chaleur_tiles',
  'reseaux_de_chaleur_tiles_pr_filtres',
  'reseaux_de_froid',
  'reseaux_de_froid_tiles',
  'zone_a_potentiel_chaud',
  'zone_a_potentiel_chaud_tiles',
  'zone_a_potentiel_fort_chaud',
  'zone_a_potentiel_fort_chaud_tiles',
  'zone_de_developpement_prioritaire',
  'zone_de_developpement_prioritaire_tiles',
  'zones_et_reseaux_en_construction',
] as const satisfies (keyof DB)[];

export const minimalDatabaseTables = [
  'api_accounts',
  'batiments_raccordes_rdc',
  'departements',
  'communes',
  'donnees_de_consos',
  'eligibility_tests',
  'eligibility_demands',
  'users',
  'email_templates',
  // 'etudes_en_cours', // non existant en prod
  // 'ign_communes', // FIXME échoue à cause de unaccent
  // 'ign_departements', // non existant en prod
  // 'ign_regions', // non existant en prod
  'jobs',
  'matomo_stats',
  'pro_comparateur_configurations',
  'pro_eligibility_tests',
  'pro_eligibility_tests_addresses',
  'reseaux_de_chaleur',
  'reseaux_de_froid',
  'zone_a_potentiel_chaud',
  'zone_a_potentiel_fort_chaud',
  'zone_de_developpement_prioritaire',
  'zones_et_reseaux_en_construction',
] satisfies (keyof DB)[];
