name: CI

# Controls when the action will run.
on: [push]

permissions:
  contents: read

jobs:
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [24]
    services:
      postgres:
        image: postgis/postgis:16-3.5-alpine
        env:
          POSTGRES_USER: fcu
          POSTGRES_PASSWORD: fcu_pass
          POSTGRES_DB: fcu_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NEXT_TELEMETRY_DISABLED: 1
      DATABASE_URL: postgres://fcu:fcu_pass@localhost:5432/fcu_db

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node 🔧
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies 💾
        run: pnpm install --frozen-lockfile

      - name: Use matching publicodes branch if any 🔀
        run: ./scripts/fetch-publicodes-branch.sh

      - name: Audit 🛡️
        run: pnpm audit
        continue-on-error: true

      - name: Lint 🧹
        run: pnpm lint:ci

      - name: Run database migrations 🔄
        run: pnpm db:migrate

      - name: Test ✅
        run: pnpm test

      - name: Build 📦
        run: pnpm build
        env:
          GITHUB_CI: true
