name: Manually triggered workflow
on:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ github.token }}
