import type { AirtableLegacyRecord } from '@/modules/demands/types';

export const demand: AirtableLegacyRecord = {
  Adresse: '15 Rue Victor Renelle 93240 Stains',
  'Affecté à': 'ENTR',
  'Code Postal': '93240',
  Conso: 464.4905,
  'Date de la demande': '2024-07-31T07:54:32.000Z',
  'Date demandes': '2024-07-31',
  Departement: 'Seine-Saint-Denis',
  'Distance au réseau': 401,
  'Emails envoyés': 'Autre',
  'en PDP': 'Oui',
  Gestionnaires: ['Stains', 'ENTR_Stains', 'ENTR', 'ENTR_IDF', 'SMIREC', 'ENTR_9301C'],
  'Gestionnaires validés': true,
  'ID BNB': '12761220',
  'ID Conso': 217610,
  'Identifiant réseau': '9301C',
  Latitude: 48.949508,
  Logement: 160,
  Longitude: 2.388623,
  Mail: 'a.martin@email.com',
  'Mode de chauffage': 'Gaz',
  Nom: 'MARTIN',
  'Nom réseau': 'Réseau de Saint Denis',
  'Notification envoyé': '2024-08-01',
  'N° de dossier': 4208,
  'Prise de contact': true,
  Prénom: 'Alain',
  Region: 'Île-de-France',
  Status: 'En attente d’éléments du prospect',
  Structure: 'Bailleur social',
  'Type de chauffage': 'Collectif',
  Téléphone: '0612345678',
  Ville: 'Stains',
};
